
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AdmissionPayment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AdmissionPayment
 * 
 */
export type AdmissionPaymentModel = runtime.Types.Result.DefaultSelection<Prisma.$AdmissionPaymentPayload>

export type AggregateAdmissionPayment = {
  _count: AdmissionPaymentCountAggregateOutputType | null
  _avg: AdmissionPaymentAvgAggregateOutputType | null
  _sum: AdmissionPaymentSumAggregateOutputType | null
  _min: AdmissionPaymentMinAggregateOutputType | null
  _max: AdmissionPaymentMaxAggregateOutputType | null
}

export type AdmissionPaymentAvgAggregateOutputType = {
  amount: runtime.Decimal | null
  discount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
}

export type AdmissionPaymentSumAggregateOutputType = {
  amount: runtime.Decimal | null
  discount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
}

export type AdmissionPaymentMinAggregateOutputType = {
  id: string | null
  studentIndexId: string | null
  studentId: string | null
  academicYearId: string | null
  amount: runtime.Decimal | null
  discount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  paymentDate: Date | null
  paymentMethod: string | null
  transactionId: string | null
  status: string | null
  remarks: string | null
  collectedById: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AdmissionPaymentMaxAggregateOutputType = {
  id: string | null
  studentIndexId: string | null
  studentId: string | null
  academicYearId: string | null
  amount: runtime.Decimal | null
  discount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  paymentDate: Date | null
  paymentMethod: string | null
  transactionId: string | null
  status: string | null
  remarks: string | null
  collectedById: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AdmissionPaymentCountAggregateOutputType = {
  id: number
  studentIndexId: number
  studentId: number
  academicYearId: number
  amount: number
  discount: number
  paidAmount: number
  paymentDate: number
  paymentMethod: number
  transactionId: number
  status: number
  remarks: number
  collectedById: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AdmissionPaymentAvgAggregateInputType = {
  amount?: true
  discount?: true
  paidAmount?: true
}

export type AdmissionPaymentSumAggregateInputType = {
  amount?: true
  discount?: true
  paidAmount?: true
}

export type AdmissionPaymentMinAggregateInputType = {
  id?: true
  studentIndexId?: true
  studentId?: true
  academicYearId?: true
  amount?: true
  discount?: true
  paidAmount?: true
  paymentDate?: true
  paymentMethod?: true
  transactionId?: true
  status?: true
  remarks?: true
  collectedById?: true
  createdAt?: true
  updatedAt?: true
}

export type AdmissionPaymentMaxAggregateInputType = {
  id?: true
  studentIndexId?: true
  studentId?: true
  academicYearId?: true
  amount?: true
  discount?: true
  paidAmount?: true
  paymentDate?: true
  paymentMethod?: true
  transactionId?: true
  status?: true
  remarks?: true
  collectedById?: true
  createdAt?: true
  updatedAt?: true
}

export type AdmissionPaymentCountAggregateInputType = {
  id?: true
  studentIndexId?: true
  studentId?: true
  academicYearId?: true
  amount?: true
  discount?: true
  paidAmount?: true
  paymentDate?: true
  paymentMethod?: true
  transactionId?: true
  status?: true
  remarks?: true
  collectedById?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AdmissionPaymentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdmissionPayment to aggregate.
   */
  where?: Prisma.AdmissionPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdmissionPayments to fetch.
   */
  orderBy?: Prisma.AdmissionPaymentOrderByWithRelationInput | Prisma.AdmissionPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AdmissionPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdmissionPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdmissionPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AdmissionPayments
  **/
  _count?: true | AdmissionPaymentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AdmissionPaymentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AdmissionPaymentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AdmissionPaymentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AdmissionPaymentMaxAggregateInputType
}

export type GetAdmissionPaymentAggregateType<T extends AdmissionPaymentAggregateArgs> = {
      [P in keyof T & keyof AggregateAdmissionPayment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdmissionPayment[P]>
    : Prisma.GetScalarType<T[P], AggregateAdmissionPayment[P]>
}




export type AdmissionPaymentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdmissionPaymentWhereInput
  orderBy?: Prisma.AdmissionPaymentOrderByWithAggregationInput | Prisma.AdmissionPaymentOrderByWithAggregationInput[]
  by: Prisma.AdmissionPaymentScalarFieldEnum[] | Prisma.AdmissionPaymentScalarFieldEnum
  having?: Prisma.AdmissionPaymentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AdmissionPaymentCountAggregateInputType | true
  _avg?: AdmissionPaymentAvgAggregateInputType
  _sum?: AdmissionPaymentSumAggregateInputType
  _min?: AdmissionPaymentMinAggregateInputType
  _max?: AdmissionPaymentMaxAggregateInputType
}

export type AdmissionPaymentGroupByOutputType = {
  id: string
  studentIndexId: string
  studentId: string
  academicYearId: string
  amount: runtime.Decimal
  discount: runtime.Decimal
  paidAmount: runtime.Decimal
  paymentDate: Date
  paymentMethod: string
  transactionId: string | null
  status: string
  remarks: string | null
  collectedById: string
  createdAt: Date
  updatedAt: Date
  _count: AdmissionPaymentCountAggregateOutputType | null
  _avg: AdmissionPaymentAvgAggregateOutputType | null
  _sum: AdmissionPaymentSumAggregateOutputType | null
  _min: AdmissionPaymentMinAggregateOutputType | null
  _max: AdmissionPaymentMaxAggregateOutputType | null
}

type GetAdmissionPaymentGroupByPayload<T extends AdmissionPaymentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AdmissionPaymentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AdmissionPaymentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AdmissionPaymentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AdmissionPaymentGroupByOutputType[P]>
      }
    >
  >



export type AdmissionPaymentWhereInput = {
  AND?: Prisma.AdmissionPaymentWhereInput | Prisma.AdmissionPaymentWhereInput[]
  OR?: Prisma.AdmissionPaymentWhereInput[]
  NOT?: Prisma.AdmissionPaymentWhereInput | Prisma.AdmissionPaymentWhereInput[]
  id?: Prisma.StringFilter<"AdmissionPayment"> | string
  studentIndexId?: Prisma.StringFilter<"AdmissionPayment"> | string
  studentId?: Prisma.StringFilter<"AdmissionPayment"> | string
  academicYearId?: Prisma.StringFilter<"AdmissionPayment"> | string
  amount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  paymentMethod?: Prisma.StringFilter<"AdmissionPayment"> | string
  transactionId?: Prisma.StringNullableFilter<"AdmissionPayment"> | string | null
  status?: Prisma.StringFilter<"AdmissionPayment"> | string
  remarks?: Prisma.StringNullableFilter<"AdmissionPayment"> | string | null
  collectedById?: Prisma.StringFilter<"AdmissionPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  academicYear?: Prisma.XOR<Prisma.AcademicYearScalarRelationFilter, Prisma.AcademicYearWhereInput>
}

export type AdmissionPaymentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  studentIndexId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  transactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  collectedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  student?: Prisma.StudentOrderByWithRelationInput
  academicYear?: Prisma.AcademicYearOrderByWithRelationInput
}

export type AdmissionPaymentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  transactionId?: string
  AND?: Prisma.AdmissionPaymentWhereInput | Prisma.AdmissionPaymentWhereInput[]
  OR?: Prisma.AdmissionPaymentWhereInput[]
  NOT?: Prisma.AdmissionPaymentWhereInput | Prisma.AdmissionPaymentWhereInput[]
  studentIndexId?: Prisma.StringFilter<"AdmissionPayment"> | string
  studentId?: Prisma.StringFilter<"AdmissionPayment"> | string
  academicYearId?: Prisma.StringFilter<"AdmissionPayment"> | string
  amount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  paymentMethod?: Prisma.StringFilter<"AdmissionPayment"> | string
  status?: Prisma.StringFilter<"AdmissionPayment"> | string
  remarks?: Prisma.StringNullableFilter<"AdmissionPayment"> | string | null
  collectedById?: Prisma.StringFilter<"AdmissionPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  academicYear?: Prisma.XOR<Prisma.AcademicYearScalarRelationFilter, Prisma.AcademicYearWhereInput>
}, "id" | "transactionId">

export type AdmissionPaymentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  studentIndexId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  transactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  collectedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AdmissionPaymentCountOrderByAggregateInput
  _avg?: Prisma.AdmissionPaymentAvgOrderByAggregateInput
  _max?: Prisma.AdmissionPaymentMaxOrderByAggregateInput
  _min?: Prisma.AdmissionPaymentMinOrderByAggregateInput
  _sum?: Prisma.AdmissionPaymentSumOrderByAggregateInput
}

export type AdmissionPaymentScalarWhereWithAggregatesInput = {
  AND?: Prisma.AdmissionPaymentScalarWhereWithAggregatesInput | Prisma.AdmissionPaymentScalarWhereWithAggregatesInput[]
  OR?: Prisma.AdmissionPaymentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AdmissionPaymentScalarWhereWithAggregatesInput | Prisma.AdmissionPaymentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AdmissionPayment"> | string
  studentIndexId?: Prisma.StringWithAggregatesFilter<"AdmissionPayment"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"AdmissionPayment"> | string
  academicYearId?: Prisma.StringWithAggregatesFilter<"AdmissionPayment"> | string
  amount?: Prisma.DecimalWithAggregatesFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalWithAggregatesFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalWithAggregatesFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeWithAggregatesFilter<"AdmissionPayment"> | Date | string
  paymentMethod?: Prisma.StringWithAggregatesFilter<"AdmissionPayment"> | string
  transactionId?: Prisma.StringNullableWithAggregatesFilter<"AdmissionPayment"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"AdmissionPayment"> | string
  remarks?: Prisma.StringNullableWithAggregatesFilter<"AdmissionPayment"> | string | null
  collectedById?: Prisma.StringWithAggregatesFilter<"AdmissionPayment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AdmissionPayment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AdmissionPayment"> | Date | string
}

export type AdmissionPaymentCreateInput = {
  id?: string
  studentIndexId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
  student: Prisma.StudentCreateNestedOneWithoutAdmissionPaymentsInput
  academicYear: Prisma.AcademicYearCreateNestedOneWithoutAdmissionPaymentsInput
}

export type AdmissionPaymentUncheckedCreateInput = {
  id?: string
  studentIndexId: string
  studentId: string
  academicYearId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdmissionPaymentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  student?: Prisma.StudentUpdateOneRequiredWithoutAdmissionPaymentsNestedInput
  academicYear?: Prisma.AcademicYearUpdateOneRequiredWithoutAdmissionPaymentsNestedInput
}

export type AdmissionPaymentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdmissionPaymentCreateManyInput = {
  id?: string
  studentIndexId: string
  studentId: string
  academicYearId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdmissionPaymentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdmissionPaymentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdmissionPaymentListRelationFilter = {
  every?: Prisma.AdmissionPaymentWhereInput
  some?: Prisma.AdmissionPaymentWhereInput
  none?: Prisma.AdmissionPaymentWhereInput
}

export type AdmissionPaymentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AdmissionPaymentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentIndexId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  collectedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AdmissionPaymentAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
}

export type AdmissionPaymentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentIndexId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  collectedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AdmissionPaymentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentIndexId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  collectedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AdmissionPaymentSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
}

export type AdmissionPaymentCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput> | Prisma.AdmissionPaymentCreateWithoutStudentInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput | Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyStudentInputEnvelope
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
}

export type AdmissionPaymentUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput> | Prisma.AdmissionPaymentCreateWithoutStudentInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput | Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyStudentInputEnvelope
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
}

export type AdmissionPaymentUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput> | Prisma.AdmissionPaymentCreateWithoutStudentInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput | Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutStudentInput | Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyStudentInputEnvelope
  set?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  disconnect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  delete?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  update?: Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutStudentInput | Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.AdmissionPaymentUpdateManyWithWhereWithoutStudentInput | Prisma.AdmissionPaymentUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.AdmissionPaymentScalarWhereInput | Prisma.AdmissionPaymentScalarWhereInput[]
}

export type AdmissionPaymentUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput> | Prisma.AdmissionPaymentCreateWithoutStudentInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput | Prisma.AdmissionPaymentCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutStudentInput | Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyStudentInputEnvelope
  set?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  disconnect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  delete?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  update?: Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutStudentInput | Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.AdmissionPaymentUpdateManyWithWhereWithoutStudentInput | Prisma.AdmissionPaymentUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.AdmissionPaymentScalarWhereInput | Prisma.AdmissionPaymentScalarWhereInput[]
}

export type AdmissionPaymentCreateNestedManyWithoutAcademicYearInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.AdmissionPaymentCreateWithoutAcademicYearInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyAcademicYearInputEnvelope
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
}

export type AdmissionPaymentUncheckedCreateNestedManyWithoutAcademicYearInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.AdmissionPaymentCreateWithoutAcademicYearInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyAcademicYearInputEnvelope
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
}

export type AdmissionPaymentUpdateManyWithoutAcademicYearNestedInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.AdmissionPaymentCreateWithoutAcademicYearInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput[]
  upsert?: Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutAcademicYearInput | Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutAcademicYearInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyAcademicYearInputEnvelope
  set?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  disconnect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  delete?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  update?: Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutAcademicYearInput | Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutAcademicYearInput[]
  updateMany?: Prisma.AdmissionPaymentUpdateManyWithWhereWithoutAcademicYearInput | Prisma.AdmissionPaymentUpdateManyWithWhereWithoutAcademicYearInput[]
  deleteMany?: Prisma.AdmissionPaymentScalarWhereInput | Prisma.AdmissionPaymentScalarWhereInput[]
}

export type AdmissionPaymentUncheckedUpdateManyWithoutAcademicYearNestedInput = {
  create?: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.AdmissionPaymentCreateWithoutAcademicYearInput[] | Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.AdmissionPaymentCreateOrConnectWithoutAcademicYearInput[]
  upsert?: Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutAcademicYearInput | Prisma.AdmissionPaymentUpsertWithWhereUniqueWithoutAcademicYearInput[]
  createMany?: Prisma.AdmissionPaymentCreateManyAcademicYearInputEnvelope
  set?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  disconnect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  delete?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  connect?: Prisma.AdmissionPaymentWhereUniqueInput | Prisma.AdmissionPaymentWhereUniqueInput[]
  update?: Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutAcademicYearInput | Prisma.AdmissionPaymentUpdateWithWhereUniqueWithoutAcademicYearInput[]
  updateMany?: Prisma.AdmissionPaymentUpdateManyWithWhereWithoutAcademicYearInput | Prisma.AdmissionPaymentUpdateManyWithWhereWithoutAcademicYearInput[]
  deleteMany?: Prisma.AdmissionPaymentScalarWhereInput | Prisma.AdmissionPaymentScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type AdmissionPaymentCreateWithoutStudentInput = {
  id?: string
  studentIndexId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
  academicYear: Prisma.AcademicYearCreateNestedOneWithoutAdmissionPaymentsInput
}

export type AdmissionPaymentUncheckedCreateWithoutStudentInput = {
  id?: string
  studentIndexId: string
  academicYearId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdmissionPaymentCreateOrConnectWithoutStudentInput = {
  where: Prisma.AdmissionPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput>
}

export type AdmissionPaymentCreateManyStudentInputEnvelope = {
  data: Prisma.AdmissionPaymentCreateManyStudentInput | Prisma.AdmissionPaymentCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type AdmissionPaymentUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.AdmissionPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.AdmissionPaymentUpdateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedCreateWithoutStudentInput>
}

export type AdmissionPaymentUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.AdmissionPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.AdmissionPaymentUpdateWithoutStudentInput, Prisma.AdmissionPaymentUncheckedUpdateWithoutStudentInput>
}

export type AdmissionPaymentUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.AdmissionPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.AdmissionPaymentUpdateManyMutationInput, Prisma.AdmissionPaymentUncheckedUpdateManyWithoutStudentInput>
}

export type AdmissionPaymentScalarWhereInput = {
  AND?: Prisma.AdmissionPaymentScalarWhereInput | Prisma.AdmissionPaymentScalarWhereInput[]
  OR?: Prisma.AdmissionPaymentScalarWhereInput[]
  NOT?: Prisma.AdmissionPaymentScalarWhereInput | Prisma.AdmissionPaymentScalarWhereInput[]
  id?: Prisma.StringFilter<"AdmissionPayment"> | string
  studentIndexId?: Prisma.StringFilter<"AdmissionPayment"> | string
  studentId?: Prisma.StringFilter<"AdmissionPayment"> | string
  academicYearId?: Prisma.StringFilter<"AdmissionPayment"> | string
  amount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"AdmissionPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  paymentMethod?: Prisma.StringFilter<"AdmissionPayment"> | string
  transactionId?: Prisma.StringNullableFilter<"AdmissionPayment"> | string | null
  status?: Prisma.StringFilter<"AdmissionPayment"> | string
  remarks?: Prisma.StringNullableFilter<"AdmissionPayment"> | string | null
  collectedById?: Prisma.StringFilter<"AdmissionPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AdmissionPayment"> | Date | string
}

export type AdmissionPaymentCreateWithoutAcademicYearInput = {
  id?: string
  studentIndexId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
  student: Prisma.StudentCreateNestedOneWithoutAdmissionPaymentsInput
}

export type AdmissionPaymentUncheckedCreateWithoutAcademicYearInput = {
  id?: string
  studentIndexId: string
  studentId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdmissionPaymentCreateOrConnectWithoutAcademicYearInput = {
  where: Prisma.AdmissionPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput>
}

export type AdmissionPaymentCreateManyAcademicYearInputEnvelope = {
  data: Prisma.AdmissionPaymentCreateManyAcademicYearInput | Prisma.AdmissionPaymentCreateManyAcademicYearInput[]
  skipDuplicates?: boolean
}

export type AdmissionPaymentUpsertWithWhereUniqueWithoutAcademicYearInput = {
  where: Prisma.AdmissionPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.AdmissionPaymentUpdateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedUpdateWithoutAcademicYearInput>
  create: Prisma.XOR<Prisma.AdmissionPaymentCreateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedCreateWithoutAcademicYearInput>
}

export type AdmissionPaymentUpdateWithWhereUniqueWithoutAcademicYearInput = {
  where: Prisma.AdmissionPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.AdmissionPaymentUpdateWithoutAcademicYearInput, Prisma.AdmissionPaymentUncheckedUpdateWithoutAcademicYearInput>
}

export type AdmissionPaymentUpdateManyWithWhereWithoutAcademicYearInput = {
  where: Prisma.AdmissionPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.AdmissionPaymentUpdateManyMutationInput, Prisma.AdmissionPaymentUncheckedUpdateManyWithoutAcademicYearInput>
}

export type AdmissionPaymentCreateManyStudentInput = {
  id?: string
  studentIndexId: string
  academicYearId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdmissionPaymentUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  academicYear?: Prisma.AcademicYearUpdateOneRequiredWithoutAdmissionPaymentsNestedInput
}

export type AdmissionPaymentUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdmissionPaymentUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdmissionPaymentCreateManyAcademicYearInput = {
  id?: string
  studentIndexId: string
  studentId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  paymentMethod: string
  transactionId?: string | null
  status?: string
  remarks?: string | null
  collectedById: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AdmissionPaymentUpdateWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  student?: Prisma.StudentUpdateOneRequiredWithoutAdmissionPaymentsNestedInput
}

export type AdmissionPaymentUncheckedUpdateWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdmissionPaymentUncheckedUpdateManyWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentIndexId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectedById?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AdmissionPaymentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentIndexId?: boolean
  studentId?: boolean
  academicYearId?: boolean
  amount?: boolean
  discount?: boolean
  paidAmount?: boolean
  paymentDate?: boolean
  paymentMethod?: boolean
  transactionId?: boolean
  status?: boolean
  remarks?: boolean
  collectedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["admissionPayment"]>

export type AdmissionPaymentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentIndexId?: boolean
  studentId?: boolean
  academicYearId?: boolean
  amount?: boolean
  discount?: boolean
  paidAmount?: boolean
  paymentDate?: boolean
  paymentMethod?: boolean
  transactionId?: boolean
  status?: boolean
  remarks?: boolean
  collectedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["admissionPayment"]>

export type AdmissionPaymentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentIndexId?: boolean
  studentId?: boolean
  academicYearId?: boolean
  amount?: boolean
  discount?: boolean
  paidAmount?: boolean
  paymentDate?: boolean
  paymentMethod?: boolean
  transactionId?: boolean
  status?: boolean
  remarks?: boolean
  collectedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["admissionPayment"]>

export type AdmissionPaymentSelectScalar = {
  id?: boolean
  studentIndexId?: boolean
  studentId?: boolean
  academicYearId?: boolean
  amount?: boolean
  discount?: boolean
  paidAmount?: boolean
  paymentDate?: boolean
  paymentMethod?: boolean
  transactionId?: boolean
  status?: boolean
  remarks?: boolean
  collectedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AdmissionPaymentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "studentIndexId" | "studentId" | "academicYearId" | "amount" | "discount" | "paidAmount" | "paymentDate" | "paymentMethod" | "transactionId" | "status" | "remarks" | "collectedById" | "createdAt" | "updatedAt", ExtArgs["result"]["admissionPayment"]>
export type AdmissionPaymentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}
export type AdmissionPaymentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}
export type AdmissionPaymentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}

export type $AdmissionPaymentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AdmissionPayment"
  objects: {
    student: Prisma.$StudentPayload<ExtArgs>
    academicYear: Prisma.$AcademicYearPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    studentIndexId: string
    studentId: string
    academicYearId: string
    amount: runtime.Decimal
    discount: runtime.Decimal
    paidAmount: runtime.Decimal
    paymentDate: Date
    paymentMethod: string
    transactionId: string | null
    status: string
    remarks: string | null
    collectedById: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["admissionPayment"]>
  composites: {}
}

export type AdmissionPaymentGetPayload<S extends boolean | null | undefined | AdmissionPaymentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload, S>

export type AdmissionPaymentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AdmissionPaymentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AdmissionPaymentCountAggregateInputType | true
  }

export interface AdmissionPaymentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AdmissionPayment'], meta: { name: 'AdmissionPayment' } }
  /**
   * Find zero or one AdmissionPayment that matches the filter.
   * @param {AdmissionPaymentFindUniqueArgs} args - Arguments to find a AdmissionPayment
   * @example
   * // Get one AdmissionPayment
   * const admissionPayment = await prisma.admissionPayment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AdmissionPaymentFindUniqueArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AdmissionPayment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AdmissionPaymentFindUniqueOrThrowArgs} args - Arguments to find a AdmissionPayment
   * @example
   * // Get one AdmissionPayment
   * const admissionPayment = await prisma.admissionPayment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AdmissionPaymentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdmissionPayment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdmissionPaymentFindFirstArgs} args - Arguments to find a AdmissionPayment
   * @example
   * // Get one AdmissionPayment
   * const admissionPayment = await prisma.admissionPayment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AdmissionPaymentFindFirstArgs>(args?: Prisma.SelectSubset<T, AdmissionPaymentFindFirstArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdmissionPayment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdmissionPaymentFindFirstOrThrowArgs} args - Arguments to find a AdmissionPayment
   * @example
   * // Get one AdmissionPayment
   * const admissionPayment = await prisma.admissionPayment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AdmissionPaymentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AdmissionPaymentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AdmissionPayments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdmissionPaymentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AdmissionPayments
   * const admissionPayments = await prisma.admissionPayment.findMany()
   * 
   * // Get first 10 AdmissionPayments
   * const admissionPayments = await prisma.admissionPayment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const admissionPaymentWithIdOnly = await prisma.admissionPayment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AdmissionPaymentFindManyArgs>(args?: Prisma.SelectSubset<T, AdmissionPaymentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AdmissionPayment.
   * @param {AdmissionPaymentCreateArgs} args - Arguments to create a AdmissionPayment.
   * @example
   * // Create one AdmissionPayment
   * const AdmissionPayment = await prisma.admissionPayment.create({
   *   data: {
   *     // ... data to create a AdmissionPayment
   *   }
   * })
   * 
   */
  create<T extends AdmissionPaymentCreateArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentCreateArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AdmissionPayments.
   * @param {AdmissionPaymentCreateManyArgs} args - Arguments to create many AdmissionPayments.
   * @example
   * // Create many AdmissionPayments
   * const admissionPayment = await prisma.admissionPayment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AdmissionPaymentCreateManyArgs>(args?: Prisma.SelectSubset<T, AdmissionPaymentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AdmissionPayments and returns the data saved in the database.
   * @param {AdmissionPaymentCreateManyAndReturnArgs} args - Arguments to create many AdmissionPayments.
   * @example
   * // Create many AdmissionPayments
   * const admissionPayment = await prisma.admissionPayment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AdmissionPayments and only return the `id`
   * const admissionPaymentWithIdOnly = await prisma.admissionPayment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AdmissionPaymentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AdmissionPaymentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AdmissionPayment.
   * @param {AdmissionPaymentDeleteArgs} args - Arguments to delete one AdmissionPayment.
   * @example
   * // Delete one AdmissionPayment
   * const AdmissionPayment = await prisma.admissionPayment.delete({
   *   where: {
   *     // ... filter to delete one AdmissionPayment
   *   }
   * })
   * 
   */
  delete<T extends AdmissionPaymentDeleteArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentDeleteArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AdmissionPayment.
   * @param {AdmissionPaymentUpdateArgs} args - Arguments to update one AdmissionPayment.
   * @example
   * // Update one AdmissionPayment
   * const admissionPayment = await prisma.admissionPayment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AdmissionPaymentUpdateArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentUpdateArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AdmissionPayments.
   * @param {AdmissionPaymentDeleteManyArgs} args - Arguments to filter AdmissionPayments to delete.
   * @example
   * // Delete a few AdmissionPayments
   * const { count } = await prisma.admissionPayment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AdmissionPaymentDeleteManyArgs>(args?: Prisma.SelectSubset<T, AdmissionPaymentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdmissionPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdmissionPaymentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AdmissionPayments
   * const admissionPayment = await prisma.admissionPayment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AdmissionPaymentUpdateManyArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdmissionPayments and returns the data updated in the database.
   * @param {AdmissionPaymentUpdateManyAndReturnArgs} args - Arguments to update many AdmissionPayments.
   * @example
   * // Update many AdmissionPayments
   * const admissionPayment = await prisma.admissionPayment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AdmissionPayments and only return the `id`
   * const admissionPaymentWithIdOnly = await prisma.admissionPayment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AdmissionPaymentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AdmissionPayment.
   * @param {AdmissionPaymentUpsertArgs} args - Arguments to update or create a AdmissionPayment.
   * @example
   * // Update or create a AdmissionPayment
   * const admissionPayment = await prisma.admissionPayment.upsert({
   *   create: {
   *     // ... data to create a AdmissionPayment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AdmissionPayment we want to update
   *   }
   * })
   */
  upsert<T extends AdmissionPaymentUpsertArgs>(args: Prisma.SelectSubset<T, AdmissionPaymentUpsertArgs<ExtArgs>>): Prisma.Prisma__AdmissionPaymentClient<runtime.Types.Result.GetResult<Prisma.$AdmissionPaymentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AdmissionPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdmissionPaymentCountArgs} args - Arguments to filter AdmissionPayments to count.
   * @example
   * // Count the number of AdmissionPayments
   * const count = await prisma.admissionPayment.count({
   *   where: {
   *     // ... the filter for the AdmissionPayments we want to count
   *   }
   * })
  **/
  count<T extends AdmissionPaymentCountArgs>(
    args?: Prisma.Subset<T, AdmissionPaymentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AdmissionPaymentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AdmissionPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdmissionPaymentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AdmissionPaymentAggregateArgs>(args: Prisma.Subset<T, AdmissionPaymentAggregateArgs>): Prisma.PrismaPromise<GetAdmissionPaymentAggregateType<T>>

  /**
   * Group by AdmissionPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdmissionPaymentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AdmissionPaymentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AdmissionPaymentGroupByArgs['orderBy'] }
      : { orderBy?: AdmissionPaymentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AdmissionPaymentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdmissionPaymentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AdmissionPayment model
 */
readonly fields: AdmissionPaymentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AdmissionPayment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AdmissionPaymentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  student<T extends Prisma.StudentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  academicYear<T extends Prisma.AcademicYearDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYearDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AdmissionPayment model
 */
export interface AdmissionPaymentFieldRefs {
  readonly id: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly studentIndexId: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly studentId: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly academicYearId: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly amount: Prisma.FieldRef<"AdmissionPayment", 'Decimal'>
  readonly discount: Prisma.FieldRef<"AdmissionPayment", 'Decimal'>
  readonly paidAmount: Prisma.FieldRef<"AdmissionPayment", 'Decimal'>
  readonly paymentDate: Prisma.FieldRef<"AdmissionPayment", 'DateTime'>
  readonly paymentMethod: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly transactionId: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly status: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly remarks: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly collectedById: Prisma.FieldRef<"AdmissionPayment", 'String'>
  readonly createdAt: Prisma.FieldRef<"AdmissionPayment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AdmissionPayment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AdmissionPayment findUnique
 */
export type AdmissionPaymentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * Filter, which AdmissionPayment to fetch.
   */
  where: Prisma.AdmissionPaymentWhereUniqueInput
}

/**
 * AdmissionPayment findUniqueOrThrow
 */
export type AdmissionPaymentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * Filter, which AdmissionPayment to fetch.
   */
  where: Prisma.AdmissionPaymentWhereUniqueInput
}

/**
 * AdmissionPayment findFirst
 */
export type AdmissionPaymentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * Filter, which AdmissionPayment to fetch.
   */
  where?: Prisma.AdmissionPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdmissionPayments to fetch.
   */
  orderBy?: Prisma.AdmissionPaymentOrderByWithRelationInput | Prisma.AdmissionPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdmissionPayments.
   */
  cursor?: Prisma.AdmissionPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdmissionPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdmissionPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdmissionPayments.
   */
  distinct?: Prisma.AdmissionPaymentScalarFieldEnum | Prisma.AdmissionPaymentScalarFieldEnum[]
}

/**
 * AdmissionPayment findFirstOrThrow
 */
export type AdmissionPaymentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * Filter, which AdmissionPayment to fetch.
   */
  where?: Prisma.AdmissionPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdmissionPayments to fetch.
   */
  orderBy?: Prisma.AdmissionPaymentOrderByWithRelationInput | Prisma.AdmissionPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdmissionPayments.
   */
  cursor?: Prisma.AdmissionPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdmissionPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdmissionPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdmissionPayments.
   */
  distinct?: Prisma.AdmissionPaymentScalarFieldEnum | Prisma.AdmissionPaymentScalarFieldEnum[]
}

/**
 * AdmissionPayment findMany
 */
export type AdmissionPaymentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * Filter, which AdmissionPayments to fetch.
   */
  where?: Prisma.AdmissionPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdmissionPayments to fetch.
   */
  orderBy?: Prisma.AdmissionPaymentOrderByWithRelationInput | Prisma.AdmissionPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AdmissionPayments.
   */
  cursor?: Prisma.AdmissionPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdmissionPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdmissionPayments.
   */
  skip?: number
  distinct?: Prisma.AdmissionPaymentScalarFieldEnum | Prisma.AdmissionPaymentScalarFieldEnum[]
}

/**
 * AdmissionPayment create
 */
export type AdmissionPaymentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * The data needed to create a AdmissionPayment.
   */
  data: Prisma.XOR<Prisma.AdmissionPaymentCreateInput, Prisma.AdmissionPaymentUncheckedCreateInput>
}

/**
 * AdmissionPayment createMany
 */
export type AdmissionPaymentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AdmissionPayments.
   */
  data: Prisma.AdmissionPaymentCreateManyInput | Prisma.AdmissionPaymentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AdmissionPayment createManyAndReturn
 */
export type AdmissionPaymentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * The data used to create many AdmissionPayments.
   */
  data: Prisma.AdmissionPaymentCreateManyInput | Prisma.AdmissionPaymentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AdmissionPayment update
 */
export type AdmissionPaymentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * The data needed to update a AdmissionPayment.
   */
  data: Prisma.XOR<Prisma.AdmissionPaymentUpdateInput, Prisma.AdmissionPaymentUncheckedUpdateInput>
  /**
   * Choose, which AdmissionPayment to update.
   */
  where: Prisma.AdmissionPaymentWhereUniqueInput
}

/**
 * AdmissionPayment updateMany
 */
export type AdmissionPaymentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AdmissionPayments.
   */
  data: Prisma.XOR<Prisma.AdmissionPaymentUpdateManyMutationInput, Prisma.AdmissionPaymentUncheckedUpdateManyInput>
  /**
   * Filter which AdmissionPayments to update
   */
  where?: Prisma.AdmissionPaymentWhereInput
  /**
   * Limit how many AdmissionPayments to update.
   */
  limit?: number
}

/**
 * AdmissionPayment updateManyAndReturn
 */
export type AdmissionPaymentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * The data used to update AdmissionPayments.
   */
  data: Prisma.XOR<Prisma.AdmissionPaymentUpdateManyMutationInput, Prisma.AdmissionPaymentUncheckedUpdateManyInput>
  /**
   * Filter which AdmissionPayments to update
   */
  where?: Prisma.AdmissionPaymentWhereInput
  /**
   * Limit how many AdmissionPayments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AdmissionPayment upsert
 */
export type AdmissionPaymentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * The filter to search for the AdmissionPayment to update in case it exists.
   */
  where: Prisma.AdmissionPaymentWhereUniqueInput
  /**
   * In case the AdmissionPayment found by the `where` argument doesn't exist, create a new AdmissionPayment with this data.
   */
  create: Prisma.XOR<Prisma.AdmissionPaymentCreateInput, Prisma.AdmissionPaymentUncheckedCreateInput>
  /**
   * In case the AdmissionPayment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AdmissionPaymentUpdateInput, Prisma.AdmissionPaymentUncheckedUpdateInput>
}

/**
 * AdmissionPayment delete
 */
export type AdmissionPaymentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
  /**
   * Filter which AdmissionPayment to delete.
   */
  where: Prisma.AdmissionPaymentWhereUniqueInput
}

/**
 * AdmissionPayment deleteMany
 */
export type AdmissionPaymentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdmissionPayments to delete
   */
  where?: Prisma.AdmissionPaymentWhereInput
  /**
   * Limit how many AdmissionPayments to delete.
   */
  limit?: number
}

/**
 * AdmissionPayment without action
 */
export type AdmissionPaymentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdmissionPayment
   */
  select?: Prisma.AdmissionPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdmissionPayment
   */
  omit?: Prisma.AdmissionPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdmissionPaymentInclude<ExtArgs> | null
}
