
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MonthlyPayment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MonthlyPayment
 * 
 */
export type MonthlyPaymentModel = runtime.Types.Result.DefaultSelection<Prisma.$MonthlyPaymentPayload>

export type AggregateMonthlyPayment = {
  _count: MonthlyPaymentCountAggregateOutputType | null
  _avg: MonthlyPaymentAvgAggregateOutputType | null
  _sum: MonthlyPaymentSumAggregateOutputType | null
  _min: MonthlyPaymentMinAggregateOutputType | null
  _max: MonthlyPaymentMaxAggregateOutputType | null
}

export type MonthlyPaymentAvgAggregateOutputType = {
  year: number | null
  baseAmount: runtime.Decimal | null
  fine: runtime.Decimal | null
  discount: runtime.Decimal | null
  totalPaid: runtime.Decimal | null
}

export type MonthlyPaymentSumAggregateOutputType = {
  year: number | null
  baseAmount: runtime.Decimal | null
  fine: runtime.Decimal | null
  discount: runtime.Decimal | null
  totalPaid: runtime.Decimal | null
}

export type MonthlyPaymentMinAggregateOutputType = {
  id: string | null
  academicYearId: string | null
  studentId: string | null
  batchId: string | null
  month: string | null
  year: number | null
  baseAmount: runtime.Decimal | null
  fine: runtime.Decimal | null
  discount: runtime.Decimal | null
  totalPaid: runtime.Decimal | null
  paymentDate: Date | null
  status: string | null
  paymentMethod: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MonthlyPaymentMaxAggregateOutputType = {
  id: string | null
  academicYearId: string | null
  studentId: string | null
  batchId: string | null
  month: string | null
  year: number | null
  baseAmount: runtime.Decimal | null
  fine: runtime.Decimal | null
  discount: runtime.Decimal | null
  totalPaid: runtime.Decimal | null
  paymentDate: Date | null
  status: string | null
  paymentMethod: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MonthlyPaymentCountAggregateOutputType = {
  id: number
  academicYearId: number
  studentId: number
  batchId: number
  month: number
  year: number
  baseAmount: number
  fine: number
  discount: number
  totalPaid: number
  paymentDate: number
  status: number
  paymentMethod: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MonthlyPaymentAvgAggregateInputType = {
  year?: true
  baseAmount?: true
  fine?: true
  discount?: true
  totalPaid?: true
}

export type MonthlyPaymentSumAggregateInputType = {
  year?: true
  baseAmount?: true
  fine?: true
  discount?: true
  totalPaid?: true
}

export type MonthlyPaymentMinAggregateInputType = {
  id?: true
  academicYearId?: true
  studentId?: true
  batchId?: true
  month?: true
  year?: true
  baseAmount?: true
  fine?: true
  discount?: true
  totalPaid?: true
  paymentDate?: true
  status?: true
  paymentMethod?: true
  createdAt?: true
  updatedAt?: true
}

export type MonthlyPaymentMaxAggregateInputType = {
  id?: true
  academicYearId?: true
  studentId?: true
  batchId?: true
  month?: true
  year?: true
  baseAmount?: true
  fine?: true
  discount?: true
  totalPaid?: true
  paymentDate?: true
  status?: true
  paymentMethod?: true
  createdAt?: true
  updatedAt?: true
}

export type MonthlyPaymentCountAggregateInputType = {
  id?: true
  academicYearId?: true
  studentId?: true
  batchId?: true
  month?: true
  year?: true
  baseAmount?: true
  fine?: true
  discount?: true
  totalPaid?: true
  paymentDate?: true
  status?: true
  paymentMethod?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MonthlyPaymentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MonthlyPayment to aggregate.
   */
  where?: Prisma.MonthlyPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyPayments to fetch.
   */
  orderBy?: Prisma.MonthlyPaymentOrderByWithRelationInput | Prisma.MonthlyPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MonthlyPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MonthlyPayments
  **/
  _count?: true | MonthlyPaymentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MonthlyPaymentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MonthlyPaymentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MonthlyPaymentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MonthlyPaymentMaxAggregateInputType
}

export type GetMonthlyPaymentAggregateType<T extends MonthlyPaymentAggregateArgs> = {
      [P in keyof T & keyof AggregateMonthlyPayment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMonthlyPayment[P]>
    : Prisma.GetScalarType<T[P], AggregateMonthlyPayment[P]>
}




export type MonthlyPaymentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MonthlyPaymentWhereInput
  orderBy?: Prisma.MonthlyPaymentOrderByWithAggregationInput | Prisma.MonthlyPaymentOrderByWithAggregationInput[]
  by: Prisma.MonthlyPaymentScalarFieldEnum[] | Prisma.MonthlyPaymentScalarFieldEnum
  having?: Prisma.MonthlyPaymentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MonthlyPaymentCountAggregateInputType | true
  _avg?: MonthlyPaymentAvgAggregateInputType
  _sum?: MonthlyPaymentSumAggregateInputType
  _min?: MonthlyPaymentMinAggregateInputType
  _max?: MonthlyPaymentMaxAggregateInputType
}

export type MonthlyPaymentGroupByOutputType = {
  id: string
  academicYearId: string
  studentId: string
  batchId: string | null
  month: string
  year: number
  baseAmount: runtime.Decimal
  fine: runtime.Decimal
  discount: runtime.Decimal
  totalPaid: runtime.Decimal
  paymentDate: Date
  status: string
  paymentMethod: string
  createdAt: Date
  updatedAt: Date
  _count: MonthlyPaymentCountAggregateOutputType | null
  _avg: MonthlyPaymentAvgAggregateOutputType | null
  _sum: MonthlyPaymentSumAggregateOutputType | null
  _min: MonthlyPaymentMinAggregateOutputType | null
  _max: MonthlyPaymentMaxAggregateOutputType | null
}

type GetMonthlyPaymentGroupByPayload<T extends MonthlyPaymentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MonthlyPaymentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MonthlyPaymentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MonthlyPaymentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MonthlyPaymentGroupByOutputType[P]>
      }
    >
  >



export type MonthlyPaymentWhereInput = {
  AND?: Prisma.MonthlyPaymentWhereInput | Prisma.MonthlyPaymentWhereInput[]
  OR?: Prisma.MonthlyPaymentWhereInput[]
  NOT?: Prisma.MonthlyPaymentWhereInput | Prisma.MonthlyPaymentWhereInput[]
  id?: Prisma.StringFilter<"MonthlyPayment"> | string
  academicYearId?: Prisma.StringFilter<"MonthlyPayment"> | string
  studentId?: Prisma.StringFilter<"MonthlyPayment"> | string
  batchId?: Prisma.StringNullableFilter<"MonthlyPayment"> | string | null
  month?: Prisma.StringFilter<"MonthlyPayment"> | string
  year?: Prisma.IntFilter<"MonthlyPayment"> | number
  baseAmount?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  status?: Prisma.StringFilter<"MonthlyPayment"> | string
  paymentMethod?: Prisma.StringFilter<"MonthlyPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  academicYear?: Prisma.XOR<Prisma.AcademicYearScalarRelationFilter, Prisma.AcademicYearWhereInput>
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  batch?: Prisma.XOR<Prisma.BatchNullableScalarRelationFilter, Prisma.BatchWhereInput> | null
}

export type MonthlyPaymentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  batchId?: Prisma.SortOrderInput | Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  baseAmount?: Prisma.SortOrder
  fine?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  totalPaid?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  academicYear?: Prisma.AcademicYearOrderByWithRelationInput
  student?: Prisma.StudentOrderByWithRelationInput
  batch?: Prisma.BatchOrderByWithRelationInput
}

export type MonthlyPaymentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  studentId_month_year?: Prisma.MonthlyPaymentStudentIdMonthYearCompoundUniqueInput
  AND?: Prisma.MonthlyPaymentWhereInput | Prisma.MonthlyPaymentWhereInput[]
  OR?: Prisma.MonthlyPaymentWhereInput[]
  NOT?: Prisma.MonthlyPaymentWhereInput | Prisma.MonthlyPaymentWhereInput[]
  academicYearId?: Prisma.StringFilter<"MonthlyPayment"> | string
  studentId?: Prisma.StringFilter<"MonthlyPayment"> | string
  batchId?: Prisma.StringNullableFilter<"MonthlyPayment"> | string | null
  month?: Prisma.StringFilter<"MonthlyPayment"> | string
  year?: Prisma.IntFilter<"MonthlyPayment"> | number
  baseAmount?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  status?: Prisma.StringFilter<"MonthlyPayment"> | string
  paymentMethod?: Prisma.StringFilter<"MonthlyPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  academicYear?: Prisma.XOR<Prisma.AcademicYearScalarRelationFilter, Prisma.AcademicYearWhereInput>
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  batch?: Prisma.XOR<Prisma.BatchNullableScalarRelationFilter, Prisma.BatchWhereInput> | null
}, "id" | "studentId_month_year">

export type MonthlyPaymentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  batchId?: Prisma.SortOrderInput | Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  baseAmount?: Prisma.SortOrder
  fine?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  totalPaid?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MonthlyPaymentCountOrderByAggregateInput
  _avg?: Prisma.MonthlyPaymentAvgOrderByAggregateInput
  _max?: Prisma.MonthlyPaymentMaxOrderByAggregateInput
  _min?: Prisma.MonthlyPaymentMinOrderByAggregateInput
  _sum?: Prisma.MonthlyPaymentSumOrderByAggregateInput
}

export type MonthlyPaymentScalarWhereWithAggregatesInput = {
  AND?: Prisma.MonthlyPaymentScalarWhereWithAggregatesInput | Prisma.MonthlyPaymentScalarWhereWithAggregatesInput[]
  OR?: Prisma.MonthlyPaymentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MonthlyPaymentScalarWhereWithAggregatesInput | Prisma.MonthlyPaymentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MonthlyPayment"> | string
  academicYearId?: Prisma.StringWithAggregatesFilter<"MonthlyPayment"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"MonthlyPayment"> | string
  batchId?: Prisma.StringNullableWithAggregatesFilter<"MonthlyPayment"> | string | null
  month?: Prisma.StringWithAggregatesFilter<"MonthlyPayment"> | string
  year?: Prisma.IntWithAggregatesFilter<"MonthlyPayment"> | number
  baseAmount?: Prisma.DecimalWithAggregatesFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalWithAggregatesFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalWithAggregatesFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalWithAggregatesFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeWithAggregatesFilter<"MonthlyPayment"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"MonthlyPayment"> | string
  paymentMethod?: Prisma.StringWithAggregatesFilter<"MonthlyPayment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MonthlyPayment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MonthlyPayment"> | Date | string
}

export type MonthlyPaymentCreateInput = {
  id?: string
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
  academicYear: Prisma.AcademicYearCreateNestedOneWithoutMonthlyPaymentsInput
  student: Prisma.StudentCreateNestedOneWithoutMonthlyPaymentsInput
  batch?: Prisma.BatchCreateNestedOneWithoutMonthlyPaymentsInput
}

export type MonthlyPaymentUncheckedCreateInput = {
  id?: string
  academicYearId: string
  studentId: string
  batchId?: string | null
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  academicYear?: Prisma.AcademicYearUpdateOneRequiredWithoutMonthlyPaymentsNestedInput
  student?: Prisma.StudentUpdateOneRequiredWithoutMonthlyPaymentsNestedInput
  batch?: Prisma.BatchUpdateOneWithoutMonthlyPaymentsNestedInput
}

export type MonthlyPaymentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentCreateManyInput = {
  id?: string
  academicYearId: string
  studentId: string
  batchId?: string | null
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentListRelationFilter = {
  every?: Prisma.MonthlyPaymentWhereInput
  some?: Prisma.MonthlyPaymentWhereInput
  none?: Prisma.MonthlyPaymentWhereInput
}

export type MonthlyPaymentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MonthlyPaymentStudentIdMonthYearCompoundUniqueInput = {
  studentId: string
  month: string
  year: number
}

export type MonthlyPaymentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  baseAmount?: Prisma.SortOrder
  fine?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  totalPaid?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MonthlyPaymentAvgOrderByAggregateInput = {
  year?: Prisma.SortOrder
  baseAmount?: Prisma.SortOrder
  fine?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  totalPaid?: Prisma.SortOrder
}

export type MonthlyPaymentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  baseAmount?: Prisma.SortOrder
  fine?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  totalPaid?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MonthlyPaymentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  baseAmount?: Prisma.SortOrder
  fine?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  totalPaid?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MonthlyPaymentSumOrderByAggregateInput = {
  year?: Prisma.SortOrder
  baseAmount?: Prisma.SortOrder
  fine?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  totalPaid?: Prisma.SortOrder
}

export type MonthlyPaymentCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput> | Prisma.MonthlyPaymentCreateWithoutStudentInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput | Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyStudentInputEnvelope
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
}

export type MonthlyPaymentUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput> | Prisma.MonthlyPaymentCreateWithoutStudentInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput | Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyStudentInputEnvelope
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
}

export type MonthlyPaymentUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput> | Prisma.MonthlyPaymentCreateWithoutStudentInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput | Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutStudentInput | Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyStudentInputEnvelope
  set?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  disconnect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  delete?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  update?: Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutStudentInput | Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.MonthlyPaymentUpdateManyWithWhereWithoutStudentInput | Prisma.MonthlyPaymentUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
}

export type MonthlyPaymentUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput> | Prisma.MonthlyPaymentCreateWithoutStudentInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput | Prisma.MonthlyPaymentCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutStudentInput | Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyStudentInputEnvelope
  set?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  disconnect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  delete?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  update?: Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutStudentInput | Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.MonthlyPaymentUpdateManyWithWhereWithoutStudentInput | Prisma.MonthlyPaymentUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
}

export type MonthlyPaymentCreateNestedManyWithoutBatchInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput> | Prisma.MonthlyPaymentCreateWithoutBatchInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput | Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyBatchInputEnvelope
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
}

export type MonthlyPaymentUncheckedCreateNestedManyWithoutBatchInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput> | Prisma.MonthlyPaymentCreateWithoutBatchInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput | Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyBatchInputEnvelope
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
}

export type MonthlyPaymentUpdateManyWithoutBatchNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput> | Prisma.MonthlyPaymentCreateWithoutBatchInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput | Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput[]
  upsert?: Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutBatchInput | Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutBatchInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyBatchInputEnvelope
  set?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  disconnect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  delete?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  update?: Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutBatchInput | Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutBatchInput[]
  updateMany?: Prisma.MonthlyPaymentUpdateManyWithWhereWithoutBatchInput | Prisma.MonthlyPaymentUpdateManyWithWhereWithoutBatchInput[]
  deleteMany?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
}

export type MonthlyPaymentUncheckedUpdateManyWithoutBatchNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput> | Prisma.MonthlyPaymentCreateWithoutBatchInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput | Prisma.MonthlyPaymentCreateOrConnectWithoutBatchInput[]
  upsert?: Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutBatchInput | Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutBatchInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyBatchInputEnvelope
  set?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  disconnect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  delete?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  update?: Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutBatchInput | Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutBatchInput[]
  updateMany?: Prisma.MonthlyPaymentUpdateManyWithWhereWithoutBatchInput | Prisma.MonthlyPaymentUpdateManyWithWhereWithoutBatchInput[]
  deleteMany?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
}

export type MonthlyPaymentCreateNestedManyWithoutAcademicYearInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.MonthlyPaymentCreateWithoutAcademicYearInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyAcademicYearInputEnvelope
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
}

export type MonthlyPaymentUncheckedCreateNestedManyWithoutAcademicYearInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.MonthlyPaymentCreateWithoutAcademicYearInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyAcademicYearInputEnvelope
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
}

export type MonthlyPaymentUpdateManyWithoutAcademicYearNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.MonthlyPaymentCreateWithoutAcademicYearInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput[]
  upsert?: Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutAcademicYearInput | Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutAcademicYearInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyAcademicYearInputEnvelope
  set?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  disconnect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  delete?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  update?: Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutAcademicYearInput | Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutAcademicYearInput[]
  updateMany?: Prisma.MonthlyPaymentUpdateManyWithWhereWithoutAcademicYearInput | Prisma.MonthlyPaymentUpdateManyWithWhereWithoutAcademicYearInput[]
  deleteMany?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
}

export type MonthlyPaymentUncheckedUpdateManyWithoutAcademicYearNestedInput = {
  create?: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput> | Prisma.MonthlyPaymentCreateWithoutAcademicYearInput[] | Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput | Prisma.MonthlyPaymentCreateOrConnectWithoutAcademicYearInput[]
  upsert?: Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutAcademicYearInput | Prisma.MonthlyPaymentUpsertWithWhereUniqueWithoutAcademicYearInput[]
  createMany?: Prisma.MonthlyPaymentCreateManyAcademicYearInputEnvelope
  set?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  disconnect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  delete?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  connect?: Prisma.MonthlyPaymentWhereUniqueInput | Prisma.MonthlyPaymentWhereUniqueInput[]
  update?: Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutAcademicYearInput | Prisma.MonthlyPaymentUpdateWithWhereUniqueWithoutAcademicYearInput[]
  updateMany?: Prisma.MonthlyPaymentUpdateManyWithWhereWithoutAcademicYearInput | Prisma.MonthlyPaymentUpdateManyWithWhereWithoutAcademicYearInput[]
  deleteMany?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
}

export type MonthlyPaymentCreateWithoutStudentInput = {
  id?: string
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
  academicYear: Prisma.AcademicYearCreateNestedOneWithoutMonthlyPaymentsInput
  batch?: Prisma.BatchCreateNestedOneWithoutMonthlyPaymentsInput
}

export type MonthlyPaymentUncheckedCreateWithoutStudentInput = {
  id?: string
  academicYearId: string
  batchId?: string | null
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentCreateOrConnectWithoutStudentInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput>
}

export type MonthlyPaymentCreateManyStudentInputEnvelope = {
  data: Prisma.MonthlyPaymentCreateManyStudentInput | Prisma.MonthlyPaymentCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type MonthlyPaymentUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.MonthlyPaymentUpdateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedCreateWithoutStudentInput>
}

export type MonthlyPaymentUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateWithoutStudentInput, Prisma.MonthlyPaymentUncheckedUpdateWithoutStudentInput>
}

export type MonthlyPaymentUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.MonthlyPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateManyMutationInput, Prisma.MonthlyPaymentUncheckedUpdateManyWithoutStudentInput>
}

export type MonthlyPaymentScalarWhereInput = {
  AND?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
  OR?: Prisma.MonthlyPaymentScalarWhereInput[]
  NOT?: Prisma.MonthlyPaymentScalarWhereInput | Prisma.MonthlyPaymentScalarWhereInput[]
  id?: Prisma.StringFilter<"MonthlyPayment"> | string
  academicYearId?: Prisma.StringFilter<"MonthlyPayment"> | string
  studentId?: Prisma.StringFilter<"MonthlyPayment"> | string
  batchId?: Prisma.StringNullableFilter<"MonthlyPayment"> | string | null
  month?: Prisma.StringFilter<"MonthlyPayment"> | string
  year?: Prisma.IntFilter<"MonthlyPayment"> | number
  baseAmount?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFilter<"MonthlyPayment"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  status?: Prisma.StringFilter<"MonthlyPayment"> | string
  paymentMethod?: Prisma.StringFilter<"MonthlyPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MonthlyPayment"> | Date | string
}

export type MonthlyPaymentCreateWithoutBatchInput = {
  id?: string
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
  academicYear: Prisma.AcademicYearCreateNestedOneWithoutMonthlyPaymentsInput
  student: Prisma.StudentCreateNestedOneWithoutMonthlyPaymentsInput
}

export type MonthlyPaymentUncheckedCreateWithoutBatchInput = {
  id?: string
  academicYearId: string
  studentId: string
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentCreateOrConnectWithoutBatchInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput>
}

export type MonthlyPaymentCreateManyBatchInputEnvelope = {
  data: Prisma.MonthlyPaymentCreateManyBatchInput | Prisma.MonthlyPaymentCreateManyBatchInput[]
  skipDuplicates?: boolean
}

export type MonthlyPaymentUpsertWithWhereUniqueWithoutBatchInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.MonthlyPaymentUpdateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedUpdateWithoutBatchInput>
  create: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedCreateWithoutBatchInput>
}

export type MonthlyPaymentUpdateWithWhereUniqueWithoutBatchInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateWithoutBatchInput, Prisma.MonthlyPaymentUncheckedUpdateWithoutBatchInput>
}

export type MonthlyPaymentUpdateManyWithWhereWithoutBatchInput = {
  where: Prisma.MonthlyPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateManyMutationInput, Prisma.MonthlyPaymentUncheckedUpdateManyWithoutBatchInput>
}

export type MonthlyPaymentCreateWithoutAcademicYearInput = {
  id?: string
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
  student: Prisma.StudentCreateNestedOneWithoutMonthlyPaymentsInput
  batch?: Prisma.BatchCreateNestedOneWithoutMonthlyPaymentsInput
}

export type MonthlyPaymentUncheckedCreateWithoutAcademicYearInput = {
  id?: string
  studentId: string
  batchId?: string | null
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentCreateOrConnectWithoutAcademicYearInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput>
}

export type MonthlyPaymentCreateManyAcademicYearInputEnvelope = {
  data: Prisma.MonthlyPaymentCreateManyAcademicYearInput | Prisma.MonthlyPaymentCreateManyAcademicYearInput[]
  skipDuplicates?: boolean
}

export type MonthlyPaymentUpsertWithWhereUniqueWithoutAcademicYearInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.MonthlyPaymentUpdateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedUpdateWithoutAcademicYearInput>
  create: Prisma.XOR<Prisma.MonthlyPaymentCreateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedCreateWithoutAcademicYearInput>
}

export type MonthlyPaymentUpdateWithWhereUniqueWithoutAcademicYearInput = {
  where: Prisma.MonthlyPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateWithoutAcademicYearInput, Prisma.MonthlyPaymentUncheckedUpdateWithoutAcademicYearInput>
}

export type MonthlyPaymentUpdateManyWithWhereWithoutAcademicYearInput = {
  where: Prisma.MonthlyPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateManyMutationInput, Prisma.MonthlyPaymentUncheckedUpdateManyWithoutAcademicYearInput>
}

export type MonthlyPaymentCreateManyStudentInput = {
  id?: string
  academicYearId: string
  batchId?: string | null
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  academicYear?: Prisma.AcademicYearUpdateOneRequiredWithoutMonthlyPaymentsNestedInput
  batch?: Prisma.BatchUpdateOneWithoutMonthlyPaymentsNestedInput
}

export type MonthlyPaymentUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentCreateManyBatchInput = {
  id?: string
  academicYearId: string
  studentId: string
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentUpdateWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  academicYear?: Prisma.AcademicYearUpdateOneRequiredWithoutMonthlyPaymentsNestedInput
  student?: Prisma.StudentUpdateOneRequiredWithoutMonthlyPaymentsNestedInput
}

export type MonthlyPaymentUncheckedUpdateWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentUncheckedUpdateManyWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentCreateManyAcademicYearInput = {
  id?: string
  studentId: string
  batchId?: string | null
  month: string
  year: number
  baseAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid: runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Date | string
  status?: string
  paymentMethod: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MonthlyPaymentUpdateWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  student?: Prisma.StudentUpdateOneRequiredWithoutMonthlyPaymentsNestedInput
  batch?: Prisma.BatchUpdateOneWithoutMonthlyPaymentsNestedInput
}

export type MonthlyPaymentUncheckedUpdateWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MonthlyPaymentUncheckedUpdateManyWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  month?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  baseAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  fine?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  discount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalPaid?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MonthlyPaymentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYearId?: boolean
  studentId?: boolean
  batchId?: boolean
  month?: boolean
  year?: boolean
  baseAmount?: boolean
  fine?: boolean
  discount?: boolean
  totalPaid?: boolean
  paymentDate?: boolean
  status?: boolean
  paymentMethod?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.MonthlyPayment$batchArgs<ExtArgs>
}, ExtArgs["result"]["monthlyPayment"]>

export type MonthlyPaymentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYearId?: boolean
  studentId?: boolean
  batchId?: boolean
  month?: boolean
  year?: boolean
  baseAmount?: boolean
  fine?: boolean
  discount?: boolean
  totalPaid?: boolean
  paymentDate?: boolean
  status?: boolean
  paymentMethod?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.MonthlyPayment$batchArgs<ExtArgs>
}, ExtArgs["result"]["monthlyPayment"]>

export type MonthlyPaymentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYearId?: boolean
  studentId?: boolean
  batchId?: boolean
  month?: boolean
  year?: boolean
  baseAmount?: boolean
  fine?: boolean
  discount?: boolean
  totalPaid?: boolean
  paymentDate?: boolean
  status?: boolean
  paymentMethod?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.MonthlyPayment$batchArgs<ExtArgs>
}, ExtArgs["result"]["monthlyPayment"]>

export type MonthlyPaymentSelectScalar = {
  id?: boolean
  academicYearId?: boolean
  studentId?: boolean
  batchId?: boolean
  month?: boolean
  year?: boolean
  baseAmount?: boolean
  fine?: boolean
  discount?: boolean
  totalPaid?: boolean
  paymentDate?: boolean
  status?: boolean
  paymentMethod?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MonthlyPaymentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "academicYearId" | "studentId" | "batchId" | "month" | "year" | "baseAmount" | "fine" | "discount" | "totalPaid" | "paymentDate" | "status" | "paymentMethod" | "createdAt" | "updatedAt", ExtArgs["result"]["monthlyPayment"]>
export type MonthlyPaymentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.MonthlyPayment$batchArgs<ExtArgs>
}
export type MonthlyPaymentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.MonthlyPayment$batchArgs<ExtArgs>
}
export type MonthlyPaymentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.MonthlyPayment$batchArgs<ExtArgs>
}

export type $MonthlyPaymentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MonthlyPayment"
  objects: {
    academicYear: Prisma.$AcademicYearPayload<ExtArgs>
    student: Prisma.$StudentPayload<ExtArgs>
    batch: Prisma.$BatchPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    academicYearId: string
    studentId: string
    batchId: string | null
    month: string
    year: number
    baseAmount: runtime.Decimal
    fine: runtime.Decimal
    discount: runtime.Decimal
    totalPaid: runtime.Decimal
    paymentDate: Date
    status: string
    paymentMethod: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["monthlyPayment"]>
  composites: {}
}

export type MonthlyPaymentGetPayload<S extends boolean | null | undefined | MonthlyPaymentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload, S>

export type MonthlyPaymentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MonthlyPaymentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MonthlyPaymentCountAggregateInputType | true
  }

export interface MonthlyPaymentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MonthlyPayment'], meta: { name: 'MonthlyPayment' } }
  /**
   * Find zero or one MonthlyPayment that matches the filter.
   * @param {MonthlyPaymentFindUniqueArgs} args - Arguments to find a MonthlyPayment
   * @example
   * // Get one MonthlyPayment
   * const monthlyPayment = await prisma.monthlyPayment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MonthlyPaymentFindUniqueArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MonthlyPayment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MonthlyPaymentFindUniqueOrThrowArgs} args - Arguments to find a MonthlyPayment
   * @example
   * // Get one MonthlyPayment
   * const monthlyPayment = await prisma.monthlyPayment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MonthlyPaymentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MonthlyPayment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyPaymentFindFirstArgs} args - Arguments to find a MonthlyPayment
   * @example
   * // Get one MonthlyPayment
   * const monthlyPayment = await prisma.monthlyPayment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MonthlyPaymentFindFirstArgs>(args?: Prisma.SelectSubset<T, MonthlyPaymentFindFirstArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MonthlyPayment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyPaymentFindFirstOrThrowArgs} args - Arguments to find a MonthlyPayment
   * @example
   * // Get one MonthlyPayment
   * const monthlyPayment = await prisma.monthlyPayment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MonthlyPaymentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MonthlyPaymentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MonthlyPayments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyPaymentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MonthlyPayments
   * const monthlyPayments = await prisma.monthlyPayment.findMany()
   * 
   * // Get first 10 MonthlyPayments
   * const monthlyPayments = await prisma.monthlyPayment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const monthlyPaymentWithIdOnly = await prisma.monthlyPayment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MonthlyPaymentFindManyArgs>(args?: Prisma.SelectSubset<T, MonthlyPaymentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MonthlyPayment.
   * @param {MonthlyPaymentCreateArgs} args - Arguments to create a MonthlyPayment.
   * @example
   * // Create one MonthlyPayment
   * const MonthlyPayment = await prisma.monthlyPayment.create({
   *   data: {
   *     // ... data to create a MonthlyPayment
   *   }
   * })
   * 
   */
  create<T extends MonthlyPaymentCreateArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentCreateArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MonthlyPayments.
   * @param {MonthlyPaymentCreateManyArgs} args - Arguments to create many MonthlyPayments.
   * @example
   * // Create many MonthlyPayments
   * const monthlyPayment = await prisma.monthlyPayment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MonthlyPaymentCreateManyArgs>(args?: Prisma.SelectSubset<T, MonthlyPaymentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MonthlyPayments and returns the data saved in the database.
   * @param {MonthlyPaymentCreateManyAndReturnArgs} args - Arguments to create many MonthlyPayments.
   * @example
   * // Create many MonthlyPayments
   * const monthlyPayment = await prisma.monthlyPayment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MonthlyPayments and only return the `id`
   * const monthlyPaymentWithIdOnly = await prisma.monthlyPayment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MonthlyPaymentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MonthlyPaymentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MonthlyPayment.
   * @param {MonthlyPaymentDeleteArgs} args - Arguments to delete one MonthlyPayment.
   * @example
   * // Delete one MonthlyPayment
   * const MonthlyPayment = await prisma.monthlyPayment.delete({
   *   where: {
   *     // ... filter to delete one MonthlyPayment
   *   }
   * })
   * 
   */
  delete<T extends MonthlyPaymentDeleteArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentDeleteArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MonthlyPayment.
   * @param {MonthlyPaymentUpdateArgs} args - Arguments to update one MonthlyPayment.
   * @example
   * // Update one MonthlyPayment
   * const monthlyPayment = await prisma.monthlyPayment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MonthlyPaymentUpdateArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentUpdateArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MonthlyPayments.
   * @param {MonthlyPaymentDeleteManyArgs} args - Arguments to filter MonthlyPayments to delete.
   * @example
   * // Delete a few MonthlyPayments
   * const { count } = await prisma.monthlyPayment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MonthlyPaymentDeleteManyArgs>(args?: Prisma.SelectSubset<T, MonthlyPaymentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MonthlyPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyPaymentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MonthlyPayments
   * const monthlyPayment = await prisma.monthlyPayment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MonthlyPaymentUpdateManyArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MonthlyPayments and returns the data updated in the database.
   * @param {MonthlyPaymentUpdateManyAndReturnArgs} args - Arguments to update many MonthlyPayments.
   * @example
   * // Update many MonthlyPayments
   * const monthlyPayment = await prisma.monthlyPayment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MonthlyPayments and only return the `id`
   * const monthlyPaymentWithIdOnly = await prisma.monthlyPayment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MonthlyPaymentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MonthlyPayment.
   * @param {MonthlyPaymentUpsertArgs} args - Arguments to update or create a MonthlyPayment.
   * @example
   * // Update or create a MonthlyPayment
   * const monthlyPayment = await prisma.monthlyPayment.upsert({
   *   create: {
   *     // ... data to create a MonthlyPayment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MonthlyPayment we want to update
   *   }
   * })
   */
  upsert<T extends MonthlyPaymentUpsertArgs>(args: Prisma.SelectSubset<T, MonthlyPaymentUpsertArgs<ExtArgs>>): Prisma.Prisma__MonthlyPaymentClient<runtime.Types.Result.GetResult<Prisma.$MonthlyPaymentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MonthlyPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyPaymentCountArgs} args - Arguments to filter MonthlyPayments to count.
   * @example
   * // Count the number of MonthlyPayments
   * const count = await prisma.monthlyPayment.count({
   *   where: {
   *     // ... the filter for the MonthlyPayments we want to count
   *   }
   * })
  **/
  count<T extends MonthlyPaymentCountArgs>(
    args?: Prisma.Subset<T, MonthlyPaymentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MonthlyPaymentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MonthlyPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyPaymentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MonthlyPaymentAggregateArgs>(args: Prisma.Subset<T, MonthlyPaymentAggregateArgs>): Prisma.PrismaPromise<GetMonthlyPaymentAggregateType<T>>

  /**
   * Group by MonthlyPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MonthlyPaymentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MonthlyPaymentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MonthlyPaymentGroupByArgs['orderBy'] }
      : { orderBy?: MonthlyPaymentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MonthlyPaymentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMonthlyPaymentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MonthlyPayment model
 */
readonly fields: MonthlyPaymentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MonthlyPayment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MonthlyPaymentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  academicYear<T extends Prisma.AcademicYearDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYearDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  student<T extends Prisma.StudentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  batch<T extends Prisma.MonthlyPayment$batchArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MonthlyPayment$batchArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MonthlyPayment model
 */
export interface MonthlyPaymentFieldRefs {
  readonly id: Prisma.FieldRef<"MonthlyPayment", 'String'>
  readonly academicYearId: Prisma.FieldRef<"MonthlyPayment", 'String'>
  readonly studentId: Prisma.FieldRef<"MonthlyPayment", 'String'>
  readonly batchId: Prisma.FieldRef<"MonthlyPayment", 'String'>
  readonly month: Prisma.FieldRef<"MonthlyPayment", 'String'>
  readonly year: Prisma.FieldRef<"MonthlyPayment", 'Int'>
  readonly baseAmount: Prisma.FieldRef<"MonthlyPayment", 'Decimal'>
  readonly fine: Prisma.FieldRef<"MonthlyPayment", 'Decimal'>
  readonly discount: Prisma.FieldRef<"MonthlyPayment", 'Decimal'>
  readonly totalPaid: Prisma.FieldRef<"MonthlyPayment", 'Decimal'>
  readonly paymentDate: Prisma.FieldRef<"MonthlyPayment", 'DateTime'>
  readonly status: Prisma.FieldRef<"MonthlyPayment", 'String'>
  readonly paymentMethod: Prisma.FieldRef<"MonthlyPayment", 'String'>
  readonly createdAt: Prisma.FieldRef<"MonthlyPayment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MonthlyPayment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MonthlyPayment findUnique
 */
export type MonthlyPaymentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyPayment to fetch.
   */
  where: Prisma.MonthlyPaymentWhereUniqueInput
}

/**
 * MonthlyPayment findUniqueOrThrow
 */
export type MonthlyPaymentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyPayment to fetch.
   */
  where: Prisma.MonthlyPaymentWhereUniqueInput
}

/**
 * MonthlyPayment findFirst
 */
export type MonthlyPaymentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyPayment to fetch.
   */
  where?: Prisma.MonthlyPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyPayments to fetch.
   */
  orderBy?: Prisma.MonthlyPaymentOrderByWithRelationInput | Prisma.MonthlyPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MonthlyPayments.
   */
  cursor?: Prisma.MonthlyPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MonthlyPayments.
   */
  distinct?: Prisma.MonthlyPaymentScalarFieldEnum | Prisma.MonthlyPaymentScalarFieldEnum[]
}

/**
 * MonthlyPayment findFirstOrThrow
 */
export type MonthlyPaymentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyPayment to fetch.
   */
  where?: Prisma.MonthlyPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyPayments to fetch.
   */
  orderBy?: Prisma.MonthlyPaymentOrderByWithRelationInput | Prisma.MonthlyPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MonthlyPayments.
   */
  cursor?: Prisma.MonthlyPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MonthlyPayments.
   */
  distinct?: Prisma.MonthlyPaymentScalarFieldEnum | Prisma.MonthlyPaymentScalarFieldEnum[]
}

/**
 * MonthlyPayment findMany
 */
export type MonthlyPaymentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * Filter, which MonthlyPayments to fetch.
   */
  where?: Prisma.MonthlyPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MonthlyPayments to fetch.
   */
  orderBy?: Prisma.MonthlyPaymentOrderByWithRelationInput | Prisma.MonthlyPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MonthlyPayments.
   */
  cursor?: Prisma.MonthlyPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MonthlyPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MonthlyPayments.
   */
  skip?: number
  distinct?: Prisma.MonthlyPaymentScalarFieldEnum | Prisma.MonthlyPaymentScalarFieldEnum[]
}

/**
 * MonthlyPayment create
 */
export type MonthlyPaymentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * The data needed to create a MonthlyPayment.
   */
  data: Prisma.XOR<Prisma.MonthlyPaymentCreateInput, Prisma.MonthlyPaymentUncheckedCreateInput>
}

/**
 * MonthlyPayment createMany
 */
export type MonthlyPaymentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MonthlyPayments.
   */
  data: Prisma.MonthlyPaymentCreateManyInput | Prisma.MonthlyPaymentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MonthlyPayment createManyAndReturn
 */
export type MonthlyPaymentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * The data used to create many MonthlyPayments.
   */
  data: Prisma.MonthlyPaymentCreateManyInput | Prisma.MonthlyPaymentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MonthlyPayment update
 */
export type MonthlyPaymentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * The data needed to update a MonthlyPayment.
   */
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateInput, Prisma.MonthlyPaymentUncheckedUpdateInput>
  /**
   * Choose, which MonthlyPayment to update.
   */
  where: Prisma.MonthlyPaymentWhereUniqueInput
}

/**
 * MonthlyPayment updateMany
 */
export type MonthlyPaymentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MonthlyPayments.
   */
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateManyMutationInput, Prisma.MonthlyPaymentUncheckedUpdateManyInput>
  /**
   * Filter which MonthlyPayments to update
   */
  where?: Prisma.MonthlyPaymentWhereInput
  /**
   * Limit how many MonthlyPayments to update.
   */
  limit?: number
}

/**
 * MonthlyPayment updateManyAndReturn
 */
export type MonthlyPaymentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * The data used to update MonthlyPayments.
   */
  data: Prisma.XOR<Prisma.MonthlyPaymentUpdateManyMutationInput, Prisma.MonthlyPaymentUncheckedUpdateManyInput>
  /**
   * Filter which MonthlyPayments to update
   */
  where?: Prisma.MonthlyPaymentWhereInput
  /**
   * Limit how many MonthlyPayments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MonthlyPayment upsert
 */
export type MonthlyPaymentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * The filter to search for the MonthlyPayment to update in case it exists.
   */
  where: Prisma.MonthlyPaymentWhereUniqueInput
  /**
   * In case the MonthlyPayment found by the `where` argument doesn't exist, create a new MonthlyPayment with this data.
   */
  create: Prisma.XOR<Prisma.MonthlyPaymentCreateInput, Prisma.MonthlyPaymentUncheckedCreateInput>
  /**
   * In case the MonthlyPayment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MonthlyPaymentUpdateInput, Prisma.MonthlyPaymentUncheckedUpdateInput>
}

/**
 * MonthlyPayment delete
 */
export type MonthlyPaymentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
  /**
   * Filter which MonthlyPayment to delete.
   */
  where: Prisma.MonthlyPaymentWhereUniqueInput
}

/**
 * MonthlyPayment deleteMany
 */
export type MonthlyPaymentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MonthlyPayments to delete
   */
  where?: Prisma.MonthlyPaymentWhereInput
  /**
   * Limit how many MonthlyPayments to delete.
   */
  limit?: number
}

/**
 * MonthlyPayment.batch
 */
export type MonthlyPayment$batchArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  where?: Prisma.BatchWhereInput
}

/**
 * MonthlyPayment without action
 */
export type MonthlyPaymentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MonthlyPayment
   */
  select?: Prisma.MonthlyPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MonthlyPayment
   */
  omit?: Prisma.MonthlyPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MonthlyPaymentInclude<ExtArgs> | null
}
