
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuestionPaperQuestion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuestionPaperQuestion
 * 
 */
export type QuestionPaperQuestionModel = runtime.Types.Result.DefaultSelection<Prisma.$QuestionPaperQuestionPayload>

export type AggregateQuestionPaperQuestion = {
  _count: QuestionPaperQuestionCountAggregateOutputType | null
  _avg: QuestionPaperQuestionAvgAggregateOutputType | null
  _sum: QuestionPaperQuestionSumAggregateOutputType | null
  _min: QuestionPaperQuestionMinAggregateOutputType | null
  _max: QuestionPaperQuestionMaxAggregateOutputType | null
}

export type QuestionPaperQuestionAvgAggregateOutputType = {
  orderIndex: number | null
}

export type QuestionPaperQuestionSumAggregateOutputType = {
  orderIndex: number | null
}

export type QuestionPaperQuestionMinAggregateOutputType = {
  id: string | null
  questionPaperId: string | null
  mcqId: string | null
  orderIndex: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionPaperQuestionMaxAggregateOutputType = {
  id: string | null
  questionPaperId: string | null
  mcqId: string | null
  orderIndex: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionPaperQuestionCountAggregateOutputType = {
  id: number
  questionPaperId: number
  mcqId: number
  orderIndex: number
  overrides: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type QuestionPaperQuestionAvgAggregateInputType = {
  orderIndex?: true
}

export type QuestionPaperQuestionSumAggregateInputType = {
  orderIndex?: true
}

export type QuestionPaperQuestionMinAggregateInputType = {
  id?: true
  questionPaperId?: true
  mcqId?: true
  orderIndex?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionPaperQuestionMaxAggregateInputType = {
  id?: true
  questionPaperId?: true
  mcqId?: true
  orderIndex?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionPaperQuestionCountAggregateInputType = {
  id?: true
  questionPaperId?: true
  mcqId?: true
  orderIndex?: true
  overrides?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type QuestionPaperQuestionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionPaperQuestion to aggregate.
   */
  where?: Prisma.QuestionPaperQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPaperQuestions to fetch.
   */
  orderBy?: Prisma.QuestionPaperQuestionOrderByWithRelationInput | Prisma.QuestionPaperQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuestionPaperQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPaperQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPaperQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuestionPaperQuestions
  **/
  _count?: true | QuestionPaperQuestionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuestionPaperQuestionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuestionPaperQuestionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuestionPaperQuestionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuestionPaperQuestionMaxAggregateInputType
}

export type GetQuestionPaperQuestionAggregateType<T extends QuestionPaperQuestionAggregateArgs> = {
      [P in keyof T & keyof AggregateQuestionPaperQuestion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuestionPaperQuestion[P]>
    : Prisma.GetScalarType<T[P], AggregateQuestionPaperQuestion[P]>
}




export type QuestionPaperQuestionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionPaperQuestionWhereInput
  orderBy?: Prisma.QuestionPaperQuestionOrderByWithAggregationInput | Prisma.QuestionPaperQuestionOrderByWithAggregationInput[]
  by: Prisma.QuestionPaperQuestionScalarFieldEnum[] | Prisma.QuestionPaperQuestionScalarFieldEnum
  having?: Prisma.QuestionPaperQuestionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuestionPaperQuestionCountAggregateInputType | true
  _avg?: QuestionPaperQuestionAvgAggregateInputType
  _sum?: QuestionPaperQuestionSumAggregateInputType
  _min?: QuestionPaperQuestionMinAggregateInputType
  _max?: QuestionPaperQuestionMaxAggregateInputType
}

export type QuestionPaperQuestionGroupByOutputType = {
  id: string
  questionPaperId: string
  mcqId: string
  orderIndex: number
  overrides: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  _count: QuestionPaperQuestionCountAggregateOutputType | null
  _avg: QuestionPaperQuestionAvgAggregateOutputType | null
  _sum: QuestionPaperQuestionSumAggregateOutputType | null
  _min: QuestionPaperQuestionMinAggregateOutputType | null
  _max: QuestionPaperQuestionMaxAggregateOutputType | null
}

type GetQuestionPaperQuestionGroupByPayload<T extends QuestionPaperQuestionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuestionPaperQuestionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuestionPaperQuestionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuestionPaperQuestionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuestionPaperQuestionGroupByOutputType[P]>
      }
    >
  >



export type QuestionPaperQuestionWhereInput = {
  AND?: Prisma.QuestionPaperQuestionWhereInput | Prisma.QuestionPaperQuestionWhereInput[]
  OR?: Prisma.QuestionPaperQuestionWhereInput[]
  NOT?: Prisma.QuestionPaperQuestionWhereInput | Prisma.QuestionPaperQuestionWhereInput[]
  id?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  questionPaperId?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  mcqId?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  orderIndex?: Prisma.IntFilter<"QuestionPaperQuestion"> | number
  overrides?: Prisma.JsonFilter<"QuestionPaperQuestion">
  createdAt?: Prisma.DateTimeFilter<"QuestionPaperQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionPaperQuestion"> | Date | string
  questionPaper?: Prisma.XOR<Prisma.QuestionPaperScalarRelationFilter, Prisma.QuestionPaperWhereInput>
}

export type QuestionPaperQuestionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  questionPaperId?: Prisma.SortOrder
  mcqId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  overrides?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  questionPaper?: Prisma.QuestionPaperOrderByWithRelationInput
}

export type QuestionPaperQuestionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  questionPaperId_mcqId?: Prisma.QuestionPaperQuestionQuestionPaperIdMcqIdCompoundUniqueInput
  AND?: Prisma.QuestionPaperQuestionWhereInput | Prisma.QuestionPaperQuestionWhereInput[]
  OR?: Prisma.QuestionPaperQuestionWhereInput[]
  NOT?: Prisma.QuestionPaperQuestionWhereInput | Prisma.QuestionPaperQuestionWhereInput[]
  questionPaperId?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  mcqId?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  orderIndex?: Prisma.IntFilter<"QuestionPaperQuestion"> | number
  overrides?: Prisma.JsonFilter<"QuestionPaperQuestion">
  createdAt?: Prisma.DateTimeFilter<"QuestionPaperQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionPaperQuestion"> | Date | string
  questionPaper?: Prisma.XOR<Prisma.QuestionPaperScalarRelationFilter, Prisma.QuestionPaperWhereInput>
}, "id" | "questionPaperId_mcqId">

export type QuestionPaperQuestionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  questionPaperId?: Prisma.SortOrder
  mcqId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  overrides?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.QuestionPaperQuestionCountOrderByAggregateInput
  _avg?: Prisma.QuestionPaperQuestionAvgOrderByAggregateInput
  _max?: Prisma.QuestionPaperQuestionMaxOrderByAggregateInput
  _min?: Prisma.QuestionPaperQuestionMinOrderByAggregateInput
  _sum?: Prisma.QuestionPaperQuestionSumOrderByAggregateInput
}

export type QuestionPaperQuestionScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuestionPaperQuestionScalarWhereWithAggregatesInput | Prisma.QuestionPaperQuestionScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuestionPaperQuestionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuestionPaperQuestionScalarWhereWithAggregatesInput | Prisma.QuestionPaperQuestionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuestionPaperQuestion"> | string
  questionPaperId?: Prisma.StringWithAggregatesFilter<"QuestionPaperQuestion"> | string
  mcqId?: Prisma.StringWithAggregatesFilter<"QuestionPaperQuestion"> | string
  orderIndex?: Prisma.IntWithAggregatesFilter<"QuestionPaperQuestion"> | number
  overrides?: Prisma.JsonWithAggregatesFilter<"QuestionPaperQuestion">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionPaperQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionPaperQuestion"> | Date | string
}

export type QuestionPaperQuestionCreateInput = {
  id?: string
  mcqId: string
  orderIndex?: number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  questionPaper: Prisma.QuestionPaperCreateNestedOneWithoutQuestionsInput
}

export type QuestionPaperQuestionUncheckedCreateInput = {
  id?: string
  questionPaperId: string
  mcqId: string
  orderIndex?: number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperQuestionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mcqId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questionPaper?: Prisma.QuestionPaperUpdateOneRequiredWithoutQuestionsNestedInput
}

export type QuestionPaperQuestionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionPaperId?: Prisma.StringFieldUpdateOperationsInput | string
  mcqId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperQuestionCreateManyInput = {
  id?: string
  questionPaperId: string
  mcqId: string
  orderIndex?: number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperQuestionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mcqId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperQuestionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionPaperId?: Prisma.StringFieldUpdateOperationsInput | string
  mcqId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperQuestionListRelationFilter = {
  every?: Prisma.QuestionPaperQuestionWhereInput
  some?: Prisma.QuestionPaperQuestionWhereInput
  none?: Prisma.QuestionPaperQuestionWhereInput
}

export type QuestionPaperQuestionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuestionPaperQuestionQuestionPaperIdMcqIdCompoundUniqueInput = {
  questionPaperId: string
  mcqId: string
}

export type QuestionPaperQuestionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionPaperId?: Prisma.SortOrder
  mcqId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  overrides?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionPaperQuestionAvgOrderByAggregateInput = {
  orderIndex?: Prisma.SortOrder
}

export type QuestionPaperQuestionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionPaperId?: Prisma.SortOrder
  mcqId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionPaperQuestionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionPaperId?: Prisma.SortOrder
  mcqId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionPaperQuestionSumOrderByAggregateInput = {
  orderIndex?: Prisma.SortOrder
}

export type QuestionPaperQuestionCreateNestedManyWithoutQuestionPaperInput = {
  create?: Prisma.XOR<Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput> | Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput[] | Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput[]
  connectOrCreate?: Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput[]
  createMany?: Prisma.QuestionPaperQuestionCreateManyQuestionPaperInputEnvelope
  connect?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
}

export type QuestionPaperQuestionUncheckedCreateNestedManyWithoutQuestionPaperInput = {
  create?: Prisma.XOR<Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput> | Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput[] | Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput[]
  connectOrCreate?: Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput[]
  createMany?: Prisma.QuestionPaperQuestionCreateManyQuestionPaperInputEnvelope
  connect?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
}

export type QuestionPaperQuestionUpdateManyWithoutQuestionPaperNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput> | Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput[] | Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput[]
  connectOrCreate?: Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput[]
  upsert?: Prisma.QuestionPaperQuestionUpsertWithWhereUniqueWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionUpsertWithWhereUniqueWithoutQuestionPaperInput[]
  createMany?: Prisma.QuestionPaperQuestionCreateManyQuestionPaperInputEnvelope
  set?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  delete?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  connect?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  update?: Prisma.QuestionPaperQuestionUpdateWithWhereUniqueWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionUpdateWithWhereUniqueWithoutQuestionPaperInput[]
  updateMany?: Prisma.QuestionPaperQuestionUpdateManyWithWhereWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionUpdateManyWithWhereWithoutQuestionPaperInput[]
  deleteMany?: Prisma.QuestionPaperQuestionScalarWhereInput | Prisma.QuestionPaperQuestionScalarWhereInput[]
}

export type QuestionPaperQuestionUncheckedUpdateManyWithoutQuestionPaperNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput> | Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput[] | Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput[]
  connectOrCreate?: Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput[]
  upsert?: Prisma.QuestionPaperQuestionUpsertWithWhereUniqueWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionUpsertWithWhereUniqueWithoutQuestionPaperInput[]
  createMany?: Prisma.QuestionPaperQuestionCreateManyQuestionPaperInputEnvelope
  set?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  delete?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  connect?: Prisma.QuestionPaperQuestionWhereUniqueInput | Prisma.QuestionPaperQuestionWhereUniqueInput[]
  update?: Prisma.QuestionPaperQuestionUpdateWithWhereUniqueWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionUpdateWithWhereUniqueWithoutQuestionPaperInput[]
  updateMany?: Prisma.QuestionPaperQuestionUpdateManyWithWhereWithoutQuestionPaperInput | Prisma.QuestionPaperQuestionUpdateManyWithWhereWithoutQuestionPaperInput[]
  deleteMany?: Prisma.QuestionPaperQuestionScalarWhereInput | Prisma.QuestionPaperQuestionScalarWhereInput[]
}

export type QuestionPaperQuestionCreateWithoutQuestionPaperInput = {
  id?: string
  mcqId: string
  orderIndex?: number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput = {
  id?: string
  mcqId: string
  orderIndex?: number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperQuestionCreateOrConnectWithoutQuestionPaperInput = {
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput>
}

export type QuestionPaperQuestionCreateManyQuestionPaperInputEnvelope = {
  data: Prisma.QuestionPaperQuestionCreateManyQuestionPaperInput | Prisma.QuestionPaperQuestionCreateManyQuestionPaperInput[]
  skipDuplicates?: boolean
}

export type QuestionPaperQuestionUpsertWithWhereUniqueWithoutQuestionPaperInput = {
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionPaperQuestionUpdateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedUpdateWithoutQuestionPaperInput>
  create: Prisma.XOR<Prisma.QuestionPaperQuestionCreateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedCreateWithoutQuestionPaperInput>
}

export type QuestionPaperQuestionUpdateWithWhereUniqueWithoutQuestionPaperInput = {
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionPaperQuestionUpdateWithoutQuestionPaperInput, Prisma.QuestionPaperQuestionUncheckedUpdateWithoutQuestionPaperInput>
}

export type QuestionPaperQuestionUpdateManyWithWhereWithoutQuestionPaperInput = {
  where: Prisma.QuestionPaperQuestionScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionPaperQuestionUpdateManyMutationInput, Prisma.QuestionPaperQuestionUncheckedUpdateManyWithoutQuestionPaperInput>
}

export type QuestionPaperQuestionScalarWhereInput = {
  AND?: Prisma.QuestionPaperQuestionScalarWhereInput | Prisma.QuestionPaperQuestionScalarWhereInput[]
  OR?: Prisma.QuestionPaperQuestionScalarWhereInput[]
  NOT?: Prisma.QuestionPaperQuestionScalarWhereInput | Prisma.QuestionPaperQuestionScalarWhereInput[]
  id?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  questionPaperId?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  mcqId?: Prisma.StringFilter<"QuestionPaperQuestion"> | string
  orderIndex?: Prisma.IntFilter<"QuestionPaperQuestion"> | number
  overrides?: Prisma.JsonFilter<"QuestionPaperQuestion">
  createdAt?: Prisma.DateTimeFilter<"QuestionPaperQuestion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionPaperQuestion"> | Date | string
}

export type QuestionPaperQuestionCreateManyQuestionPaperInput = {
  id?: string
  mcqId: string
  orderIndex?: number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperQuestionUpdateWithoutQuestionPaperInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mcqId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperQuestionUncheckedUpdateWithoutQuestionPaperInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mcqId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperQuestionUncheckedUpdateManyWithoutQuestionPaperInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mcqId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  overrides?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type QuestionPaperQuestionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionPaperId?: boolean
  mcqId?: boolean
  orderIndex?: boolean
  overrides?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  questionPaper?: boolean | Prisma.QuestionPaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionPaperQuestion"]>

export type QuestionPaperQuestionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionPaperId?: boolean
  mcqId?: boolean
  orderIndex?: boolean
  overrides?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  questionPaper?: boolean | Prisma.QuestionPaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionPaperQuestion"]>

export type QuestionPaperQuestionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionPaperId?: boolean
  mcqId?: boolean
  orderIndex?: boolean
  overrides?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  questionPaper?: boolean | Prisma.QuestionPaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionPaperQuestion"]>

export type QuestionPaperQuestionSelectScalar = {
  id?: boolean
  questionPaperId?: boolean
  mcqId?: boolean
  orderIndex?: boolean
  overrides?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type QuestionPaperQuestionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "questionPaperId" | "mcqId" | "orderIndex" | "overrides" | "createdAt" | "updatedAt", ExtArgs["result"]["questionPaperQuestion"]>
export type QuestionPaperQuestionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  questionPaper?: boolean | Prisma.QuestionPaperDefaultArgs<ExtArgs>
}
export type QuestionPaperQuestionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  questionPaper?: boolean | Prisma.QuestionPaperDefaultArgs<ExtArgs>
}
export type QuestionPaperQuestionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  questionPaper?: boolean | Prisma.QuestionPaperDefaultArgs<ExtArgs>
}

export type $QuestionPaperQuestionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuestionPaperQuestion"
  objects: {
    questionPaper: Prisma.$QuestionPaperPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    questionPaperId: string
    mcqId: string
    orderIndex: number
    overrides: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["questionPaperQuestion"]>
  composites: {}
}

export type QuestionPaperQuestionGetPayload<S extends boolean | null | undefined | QuestionPaperQuestionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload, S>

export type QuestionPaperQuestionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuestionPaperQuestionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuestionPaperQuestionCountAggregateInputType | true
  }

export interface QuestionPaperQuestionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuestionPaperQuestion'], meta: { name: 'QuestionPaperQuestion' } }
  /**
   * Find zero or one QuestionPaperQuestion that matches the filter.
   * @param {QuestionPaperQuestionFindUniqueArgs} args - Arguments to find a QuestionPaperQuestion
   * @example
   * // Get one QuestionPaperQuestion
   * const questionPaperQuestion = await prisma.questionPaperQuestion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuestionPaperQuestionFindUniqueArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuestionPaperQuestion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuestionPaperQuestionFindUniqueOrThrowArgs} args - Arguments to find a QuestionPaperQuestion
   * @example
   * // Get one QuestionPaperQuestion
   * const questionPaperQuestion = await prisma.questionPaperQuestion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuestionPaperQuestionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionPaperQuestion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperQuestionFindFirstArgs} args - Arguments to find a QuestionPaperQuestion
   * @example
   * // Get one QuestionPaperQuestion
   * const questionPaperQuestion = await prisma.questionPaperQuestion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuestionPaperQuestionFindFirstArgs>(args?: Prisma.SelectSubset<T, QuestionPaperQuestionFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionPaperQuestion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperQuestionFindFirstOrThrowArgs} args - Arguments to find a QuestionPaperQuestion
   * @example
   * // Get one QuestionPaperQuestion
   * const questionPaperQuestion = await prisma.questionPaperQuestion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuestionPaperQuestionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuestionPaperQuestionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuestionPaperQuestions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperQuestionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuestionPaperQuestions
   * const questionPaperQuestions = await prisma.questionPaperQuestion.findMany()
   * 
   * // Get first 10 QuestionPaperQuestions
   * const questionPaperQuestions = await prisma.questionPaperQuestion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const questionPaperQuestionWithIdOnly = await prisma.questionPaperQuestion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuestionPaperQuestionFindManyArgs>(args?: Prisma.SelectSubset<T, QuestionPaperQuestionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuestionPaperQuestion.
   * @param {QuestionPaperQuestionCreateArgs} args - Arguments to create a QuestionPaperQuestion.
   * @example
   * // Create one QuestionPaperQuestion
   * const QuestionPaperQuestion = await prisma.questionPaperQuestion.create({
   *   data: {
   *     // ... data to create a QuestionPaperQuestion
   *   }
   * })
   * 
   */
  create<T extends QuestionPaperQuestionCreateArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionCreateArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuestionPaperQuestions.
   * @param {QuestionPaperQuestionCreateManyArgs} args - Arguments to create many QuestionPaperQuestions.
   * @example
   * // Create many QuestionPaperQuestions
   * const questionPaperQuestion = await prisma.questionPaperQuestion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuestionPaperQuestionCreateManyArgs>(args?: Prisma.SelectSubset<T, QuestionPaperQuestionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuestionPaperQuestions and returns the data saved in the database.
   * @param {QuestionPaperQuestionCreateManyAndReturnArgs} args - Arguments to create many QuestionPaperQuestions.
   * @example
   * // Create many QuestionPaperQuestions
   * const questionPaperQuestion = await prisma.questionPaperQuestion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuestionPaperQuestions and only return the `id`
   * const questionPaperQuestionWithIdOnly = await prisma.questionPaperQuestion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuestionPaperQuestionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuestionPaperQuestionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuestionPaperQuestion.
   * @param {QuestionPaperQuestionDeleteArgs} args - Arguments to delete one QuestionPaperQuestion.
   * @example
   * // Delete one QuestionPaperQuestion
   * const QuestionPaperQuestion = await prisma.questionPaperQuestion.delete({
   *   where: {
   *     // ... filter to delete one QuestionPaperQuestion
   *   }
   * })
   * 
   */
  delete<T extends QuestionPaperQuestionDeleteArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionDeleteArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuestionPaperQuestion.
   * @param {QuestionPaperQuestionUpdateArgs} args - Arguments to update one QuestionPaperQuestion.
   * @example
   * // Update one QuestionPaperQuestion
   * const questionPaperQuestion = await prisma.questionPaperQuestion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuestionPaperQuestionUpdateArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionUpdateArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuestionPaperQuestions.
   * @param {QuestionPaperQuestionDeleteManyArgs} args - Arguments to filter QuestionPaperQuestions to delete.
   * @example
   * // Delete a few QuestionPaperQuestions
   * const { count } = await prisma.questionPaperQuestion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuestionPaperQuestionDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuestionPaperQuestionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionPaperQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperQuestionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuestionPaperQuestions
   * const questionPaperQuestion = await prisma.questionPaperQuestion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuestionPaperQuestionUpdateManyArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionPaperQuestions and returns the data updated in the database.
   * @param {QuestionPaperQuestionUpdateManyAndReturnArgs} args - Arguments to update many QuestionPaperQuestions.
   * @example
   * // Update many QuestionPaperQuestions
   * const questionPaperQuestion = await prisma.questionPaperQuestion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuestionPaperQuestions and only return the `id`
   * const questionPaperQuestionWithIdOnly = await prisma.questionPaperQuestion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuestionPaperQuestionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuestionPaperQuestion.
   * @param {QuestionPaperQuestionUpsertArgs} args - Arguments to update or create a QuestionPaperQuestion.
   * @example
   * // Update or create a QuestionPaperQuestion
   * const questionPaperQuestion = await prisma.questionPaperQuestion.upsert({
   *   create: {
   *     // ... data to create a QuestionPaperQuestion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuestionPaperQuestion we want to update
   *   }
   * })
   */
  upsert<T extends QuestionPaperQuestionUpsertArgs>(args: Prisma.SelectSubset<T, QuestionPaperQuestionUpsertArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperQuestionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuestionPaperQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperQuestionCountArgs} args - Arguments to filter QuestionPaperQuestions to count.
   * @example
   * // Count the number of QuestionPaperQuestions
   * const count = await prisma.questionPaperQuestion.count({
   *   where: {
   *     // ... the filter for the QuestionPaperQuestions we want to count
   *   }
   * })
  **/
  count<T extends QuestionPaperQuestionCountArgs>(
    args?: Prisma.Subset<T, QuestionPaperQuestionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuestionPaperQuestionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuestionPaperQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperQuestionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuestionPaperQuestionAggregateArgs>(args: Prisma.Subset<T, QuestionPaperQuestionAggregateArgs>): Prisma.PrismaPromise<GetQuestionPaperQuestionAggregateType<T>>

  /**
   * Group by QuestionPaperQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperQuestionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuestionPaperQuestionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuestionPaperQuestionGroupByArgs['orderBy'] }
      : { orderBy?: QuestionPaperQuestionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuestionPaperQuestionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuestionPaperQuestionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuestionPaperQuestion model
 */
readonly fields: QuestionPaperQuestionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuestionPaperQuestion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuestionPaperQuestionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  questionPaper<T extends Prisma.QuestionPaperDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionPaperDefaultArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuestionPaperQuestion model
 */
export interface QuestionPaperQuestionFieldRefs {
  readonly id: Prisma.FieldRef<"QuestionPaperQuestion", 'String'>
  readonly questionPaperId: Prisma.FieldRef<"QuestionPaperQuestion", 'String'>
  readonly mcqId: Prisma.FieldRef<"QuestionPaperQuestion", 'String'>
  readonly orderIndex: Prisma.FieldRef<"QuestionPaperQuestion", 'Int'>
  readonly overrides: Prisma.FieldRef<"QuestionPaperQuestion", 'Json'>
  readonly createdAt: Prisma.FieldRef<"QuestionPaperQuestion", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"QuestionPaperQuestion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuestionPaperQuestion findUnique
 */
export type QuestionPaperQuestionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuestionPaperQuestion to fetch.
   */
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
}

/**
 * QuestionPaperQuestion findUniqueOrThrow
 */
export type QuestionPaperQuestionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuestionPaperQuestion to fetch.
   */
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
}

/**
 * QuestionPaperQuestion findFirst
 */
export type QuestionPaperQuestionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuestionPaperQuestion to fetch.
   */
  where?: Prisma.QuestionPaperQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPaperQuestions to fetch.
   */
  orderBy?: Prisma.QuestionPaperQuestionOrderByWithRelationInput | Prisma.QuestionPaperQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionPaperQuestions.
   */
  cursor?: Prisma.QuestionPaperQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPaperQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPaperQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionPaperQuestions.
   */
  distinct?: Prisma.QuestionPaperQuestionScalarFieldEnum | Prisma.QuestionPaperQuestionScalarFieldEnum[]
}

/**
 * QuestionPaperQuestion findFirstOrThrow
 */
export type QuestionPaperQuestionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuestionPaperQuestion to fetch.
   */
  where?: Prisma.QuestionPaperQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPaperQuestions to fetch.
   */
  orderBy?: Prisma.QuestionPaperQuestionOrderByWithRelationInput | Prisma.QuestionPaperQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionPaperQuestions.
   */
  cursor?: Prisma.QuestionPaperQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPaperQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPaperQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionPaperQuestions.
   */
  distinct?: Prisma.QuestionPaperQuestionScalarFieldEnum | Prisma.QuestionPaperQuestionScalarFieldEnum[]
}

/**
 * QuestionPaperQuestion findMany
 */
export type QuestionPaperQuestionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuestionPaperQuestions to fetch.
   */
  where?: Prisma.QuestionPaperQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPaperQuestions to fetch.
   */
  orderBy?: Prisma.QuestionPaperQuestionOrderByWithRelationInput | Prisma.QuestionPaperQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuestionPaperQuestions.
   */
  cursor?: Prisma.QuestionPaperQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPaperQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPaperQuestions.
   */
  skip?: number
  distinct?: Prisma.QuestionPaperQuestionScalarFieldEnum | Prisma.QuestionPaperQuestionScalarFieldEnum[]
}

/**
 * QuestionPaperQuestion create
 */
export type QuestionPaperQuestionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * The data needed to create a QuestionPaperQuestion.
   */
  data: Prisma.XOR<Prisma.QuestionPaperQuestionCreateInput, Prisma.QuestionPaperQuestionUncheckedCreateInput>
}

/**
 * QuestionPaperQuestion createMany
 */
export type QuestionPaperQuestionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuestionPaperQuestions.
   */
  data: Prisma.QuestionPaperQuestionCreateManyInput | Prisma.QuestionPaperQuestionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuestionPaperQuestion createManyAndReturn
 */
export type QuestionPaperQuestionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * The data used to create many QuestionPaperQuestions.
   */
  data: Prisma.QuestionPaperQuestionCreateManyInput | Prisma.QuestionPaperQuestionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionPaperQuestion update
 */
export type QuestionPaperQuestionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * The data needed to update a QuestionPaperQuestion.
   */
  data: Prisma.XOR<Prisma.QuestionPaperQuestionUpdateInput, Prisma.QuestionPaperQuestionUncheckedUpdateInput>
  /**
   * Choose, which QuestionPaperQuestion to update.
   */
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
}

/**
 * QuestionPaperQuestion updateMany
 */
export type QuestionPaperQuestionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuestionPaperQuestions.
   */
  data: Prisma.XOR<Prisma.QuestionPaperQuestionUpdateManyMutationInput, Prisma.QuestionPaperQuestionUncheckedUpdateManyInput>
  /**
   * Filter which QuestionPaperQuestions to update
   */
  where?: Prisma.QuestionPaperQuestionWhereInput
  /**
   * Limit how many QuestionPaperQuestions to update.
   */
  limit?: number
}

/**
 * QuestionPaperQuestion updateManyAndReturn
 */
export type QuestionPaperQuestionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * The data used to update QuestionPaperQuestions.
   */
  data: Prisma.XOR<Prisma.QuestionPaperQuestionUpdateManyMutationInput, Prisma.QuestionPaperQuestionUncheckedUpdateManyInput>
  /**
   * Filter which QuestionPaperQuestions to update
   */
  where?: Prisma.QuestionPaperQuestionWhereInput
  /**
   * Limit how many QuestionPaperQuestions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionPaperQuestion upsert
 */
export type QuestionPaperQuestionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * The filter to search for the QuestionPaperQuestion to update in case it exists.
   */
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
  /**
   * In case the QuestionPaperQuestion found by the `where` argument doesn't exist, create a new QuestionPaperQuestion with this data.
   */
  create: Prisma.XOR<Prisma.QuestionPaperQuestionCreateInput, Prisma.QuestionPaperQuestionUncheckedCreateInput>
  /**
   * In case the QuestionPaperQuestion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuestionPaperQuestionUpdateInput, Prisma.QuestionPaperQuestionUncheckedUpdateInput>
}

/**
 * QuestionPaperQuestion delete
 */
export type QuestionPaperQuestionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
  /**
   * Filter which QuestionPaperQuestion to delete.
   */
  where: Prisma.QuestionPaperQuestionWhereUniqueInput
}

/**
 * QuestionPaperQuestion deleteMany
 */
export type QuestionPaperQuestionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionPaperQuestions to delete
   */
  where?: Prisma.QuestionPaperQuestionWhereInput
  /**
   * Limit how many QuestionPaperQuestions to delete.
   */
  limit?: number
}

/**
 * QuestionPaperQuestion without action
 */
export type QuestionPaperQuestionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaperQuestion
   */
  select?: Prisma.QuestionPaperQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaperQuestion
   */
  omit?: Prisma.QuestionPaperQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperQuestionInclude<ExtArgs> | null
}
