
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuestionType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuestionType
 * 
 */
export type QuestionTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$QuestionTypePayload>

export type AggregateQuestionType = {
  _count: QuestionTypeCountAggregateOutputType | null
  _min: QuestionTypeMinAggregateOutputType | null
  _max: QuestionTypeMaxAggregateOutputType | null
}

export type QuestionTypeMinAggregateOutputType = {
  id: string | null
  name: string | null
  displayName: string | null
  subjectId: string | null
  chapterId: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionTypeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  displayName: string | null
  subjectId: string | null
  chapterId: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionTypeCountAggregateOutputType = {
  id: number
  name: number
  displayName: number
  subjectId: number
  chapterId: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type QuestionTypeMinAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  subjectId?: true
  chapterId?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionTypeMaxAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  subjectId?: true
  chapterId?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionTypeCountAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  subjectId?: true
  chapterId?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type QuestionTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionType to aggregate.
   */
  where?: Prisma.QuestionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionTypes to fetch.
   */
  orderBy?: Prisma.QuestionTypeOrderByWithRelationInput | Prisma.QuestionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuestionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuestionTypes
  **/
  _count?: true | QuestionTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuestionTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuestionTypeMaxAggregateInputType
}

export type GetQuestionTypeAggregateType<T extends QuestionTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateQuestionType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuestionType[P]>
    : Prisma.GetScalarType<T[P], AggregateQuestionType[P]>
}




export type QuestionTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionTypeWhereInput
  orderBy?: Prisma.QuestionTypeOrderByWithAggregationInput | Prisma.QuestionTypeOrderByWithAggregationInput[]
  by: Prisma.QuestionTypeScalarFieldEnum[] | Prisma.QuestionTypeScalarFieldEnum
  having?: Prisma.QuestionTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuestionTypeCountAggregateInputType | true
  _min?: QuestionTypeMinAggregateInputType
  _max?: QuestionTypeMaxAggregateInputType
}

export type QuestionTypeGroupByOutputType = {
  id: string
  name: string
  displayName: string
  subjectId: string
  chapterId: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: QuestionTypeCountAggregateOutputType | null
  _min: QuestionTypeMinAggregateOutputType | null
  _max: QuestionTypeMaxAggregateOutputType | null
}

type GetQuestionTypeGroupByPayload<T extends QuestionTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuestionTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuestionTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuestionTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuestionTypeGroupByOutputType[P]>
      }
    >
  >



export type QuestionTypeWhereInput = {
  AND?: Prisma.QuestionTypeWhereInput | Prisma.QuestionTypeWhereInput[]
  OR?: Prisma.QuestionTypeWhereInput[]
  NOT?: Prisma.QuestionTypeWhereInput | Prisma.QuestionTypeWhereInput[]
  id?: Prisma.StringFilter<"QuestionType"> | string
  name?: Prisma.StringFilter<"QuestionType"> | string
  displayName?: Prisma.StringFilter<"QuestionType"> | string
  subjectId?: Prisma.StringFilter<"QuestionType"> | string
  chapterId?: Prisma.StringNullableFilter<"QuestionType"> | string | null
  isActive?: Prisma.BoolFilter<"QuestionType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"QuestionType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionType"> | Date | string
  subject?: Prisma.XOR<Prisma.AcademicSubjectScalarRelationFilter, Prisma.AcademicSubjectWhereInput>
  chapter?: Prisma.XOR<Prisma.AcademicChapterNullableScalarRelationFilter, Prisma.AcademicChapterWhereInput> | null
}

export type QuestionTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subject?: Prisma.AcademicSubjectOrderByWithRelationInput
  chapter?: Prisma.AcademicChapterOrderByWithRelationInput
}

export type QuestionTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.QuestionTypeWhereInput | Prisma.QuestionTypeWhereInput[]
  OR?: Prisma.QuestionTypeWhereInput[]
  NOT?: Prisma.QuestionTypeWhereInput | Prisma.QuestionTypeWhereInput[]
  name?: Prisma.StringFilter<"QuestionType"> | string
  displayName?: Prisma.StringFilter<"QuestionType"> | string
  subjectId?: Prisma.StringFilter<"QuestionType"> | string
  chapterId?: Prisma.StringNullableFilter<"QuestionType"> | string | null
  isActive?: Prisma.BoolFilter<"QuestionType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"QuestionType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionType"> | Date | string
  subject?: Prisma.XOR<Prisma.AcademicSubjectScalarRelationFilter, Prisma.AcademicSubjectWhereInput>
  chapter?: Prisma.XOR<Prisma.AcademicChapterNullableScalarRelationFilter, Prisma.AcademicChapterWhereInput> | null
}, "id">

export type QuestionTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.QuestionTypeCountOrderByAggregateInput
  _max?: Prisma.QuestionTypeMaxOrderByAggregateInput
  _min?: Prisma.QuestionTypeMinOrderByAggregateInput
}

export type QuestionTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuestionTypeScalarWhereWithAggregatesInput | Prisma.QuestionTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuestionTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuestionTypeScalarWhereWithAggregatesInput | Prisma.QuestionTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuestionType"> | string
  name?: Prisma.StringWithAggregatesFilter<"QuestionType"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"QuestionType"> | string
  subjectId?: Prisma.StringWithAggregatesFilter<"QuestionType"> | string
  chapterId?: Prisma.StringNullableWithAggregatesFilter<"QuestionType"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"QuestionType"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionType"> | Date | string
}

export type QuestionTypeCreateInput = {
  id?: string
  name: string
  displayName: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subject: Prisma.AcademicSubjectCreateNestedOneWithoutQuestionTypesInput
  chapter?: Prisma.AcademicChapterCreateNestedOneWithoutQuestionTypesInput
}

export type QuestionTypeUncheckedCreateInput = {
  id?: string
  name: string
  displayName: string
  subjectId: string
  chapterId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject?: Prisma.AcademicSubjectUpdateOneRequiredWithoutQuestionTypesNestedInput
  chapter?: Prisma.AcademicChapterUpdateOneWithoutQuestionTypesNestedInput
}

export type QuestionTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionTypeCreateManyInput = {
  id?: string
  name: string
  displayName: string
  subjectId: string
  chapterId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionTypeListRelationFilter = {
  every?: Prisma.QuestionTypeWhereInput
  some?: Prisma.QuestionTypeWhereInput
  none?: Prisma.QuestionTypeWhereInput
}

export type QuestionTypeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuestionTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionTypeCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutSubjectInput, Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput> | Prisma.QuestionTypeCreateWithoutSubjectInput[] | Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput | Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.QuestionTypeCreateManySubjectInputEnvelope
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
}

export type QuestionTypeUncheckedCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutSubjectInput, Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput> | Prisma.QuestionTypeCreateWithoutSubjectInput[] | Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput | Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.QuestionTypeCreateManySubjectInputEnvelope
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
}

export type QuestionTypeUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutSubjectInput, Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput> | Prisma.QuestionTypeCreateWithoutSubjectInput[] | Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput | Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.QuestionTypeUpsertWithWhereUniqueWithoutSubjectInput | Prisma.QuestionTypeUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.QuestionTypeCreateManySubjectInputEnvelope
  set?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  disconnect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  delete?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  update?: Prisma.QuestionTypeUpdateWithWhereUniqueWithoutSubjectInput | Prisma.QuestionTypeUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.QuestionTypeUpdateManyWithWhereWithoutSubjectInput | Prisma.QuestionTypeUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.QuestionTypeScalarWhereInput | Prisma.QuestionTypeScalarWhereInput[]
}

export type QuestionTypeUncheckedUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutSubjectInput, Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput> | Prisma.QuestionTypeCreateWithoutSubjectInput[] | Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput | Prisma.QuestionTypeCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.QuestionTypeUpsertWithWhereUniqueWithoutSubjectInput | Prisma.QuestionTypeUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.QuestionTypeCreateManySubjectInputEnvelope
  set?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  disconnect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  delete?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  update?: Prisma.QuestionTypeUpdateWithWhereUniqueWithoutSubjectInput | Prisma.QuestionTypeUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.QuestionTypeUpdateManyWithWhereWithoutSubjectInput | Prisma.QuestionTypeUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.QuestionTypeScalarWhereInput | Prisma.QuestionTypeScalarWhereInput[]
}

export type QuestionTypeCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutChapterInput, Prisma.QuestionTypeUncheckedCreateWithoutChapterInput> | Prisma.QuestionTypeCreateWithoutChapterInput[] | Prisma.QuestionTypeUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutChapterInput | Prisma.QuestionTypeCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.QuestionTypeCreateManyChapterInputEnvelope
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
}

export type QuestionTypeUncheckedCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutChapterInput, Prisma.QuestionTypeUncheckedCreateWithoutChapterInput> | Prisma.QuestionTypeCreateWithoutChapterInput[] | Prisma.QuestionTypeUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutChapterInput | Prisma.QuestionTypeCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.QuestionTypeCreateManyChapterInputEnvelope
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
}

export type QuestionTypeUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutChapterInput, Prisma.QuestionTypeUncheckedCreateWithoutChapterInput> | Prisma.QuestionTypeCreateWithoutChapterInput[] | Prisma.QuestionTypeUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutChapterInput | Prisma.QuestionTypeCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.QuestionTypeUpsertWithWhereUniqueWithoutChapterInput | Prisma.QuestionTypeUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.QuestionTypeCreateManyChapterInputEnvelope
  set?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  disconnect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  delete?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  update?: Prisma.QuestionTypeUpdateWithWhereUniqueWithoutChapterInput | Prisma.QuestionTypeUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.QuestionTypeUpdateManyWithWhereWithoutChapterInput | Prisma.QuestionTypeUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.QuestionTypeScalarWhereInput | Prisma.QuestionTypeScalarWhereInput[]
}

export type QuestionTypeUncheckedUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionTypeCreateWithoutChapterInput, Prisma.QuestionTypeUncheckedCreateWithoutChapterInput> | Prisma.QuestionTypeCreateWithoutChapterInput[] | Prisma.QuestionTypeUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.QuestionTypeCreateOrConnectWithoutChapterInput | Prisma.QuestionTypeCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.QuestionTypeUpsertWithWhereUniqueWithoutChapterInput | Prisma.QuestionTypeUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.QuestionTypeCreateManyChapterInputEnvelope
  set?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  disconnect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  delete?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  connect?: Prisma.QuestionTypeWhereUniqueInput | Prisma.QuestionTypeWhereUniqueInput[]
  update?: Prisma.QuestionTypeUpdateWithWhereUniqueWithoutChapterInput | Prisma.QuestionTypeUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.QuestionTypeUpdateManyWithWhereWithoutChapterInput | Prisma.QuestionTypeUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.QuestionTypeScalarWhereInput | Prisma.QuestionTypeScalarWhereInput[]
}

export type QuestionTypeCreateWithoutSubjectInput = {
  id?: string
  name: string
  displayName: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  chapter?: Prisma.AcademicChapterCreateNestedOneWithoutQuestionTypesInput
}

export type QuestionTypeUncheckedCreateWithoutSubjectInput = {
  id?: string
  name: string
  displayName: string
  chapterId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionTypeCreateOrConnectWithoutSubjectInput = {
  where: Prisma.QuestionTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionTypeCreateWithoutSubjectInput, Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput>
}

export type QuestionTypeCreateManySubjectInputEnvelope = {
  data: Prisma.QuestionTypeCreateManySubjectInput | Prisma.QuestionTypeCreateManySubjectInput[]
  skipDuplicates?: boolean
}

export type QuestionTypeUpsertWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.QuestionTypeWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionTypeUpdateWithoutSubjectInput, Prisma.QuestionTypeUncheckedUpdateWithoutSubjectInput>
  create: Prisma.XOR<Prisma.QuestionTypeCreateWithoutSubjectInput, Prisma.QuestionTypeUncheckedCreateWithoutSubjectInput>
}

export type QuestionTypeUpdateWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.QuestionTypeWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionTypeUpdateWithoutSubjectInput, Prisma.QuestionTypeUncheckedUpdateWithoutSubjectInput>
}

export type QuestionTypeUpdateManyWithWhereWithoutSubjectInput = {
  where: Prisma.QuestionTypeScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionTypeUpdateManyMutationInput, Prisma.QuestionTypeUncheckedUpdateManyWithoutSubjectInput>
}

export type QuestionTypeScalarWhereInput = {
  AND?: Prisma.QuestionTypeScalarWhereInput | Prisma.QuestionTypeScalarWhereInput[]
  OR?: Prisma.QuestionTypeScalarWhereInput[]
  NOT?: Prisma.QuestionTypeScalarWhereInput | Prisma.QuestionTypeScalarWhereInput[]
  id?: Prisma.StringFilter<"QuestionType"> | string
  name?: Prisma.StringFilter<"QuestionType"> | string
  displayName?: Prisma.StringFilter<"QuestionType"> | string
  subjectId?: Prisma.StringFilter<"QuestionType"> | string
  chapterId?: Prisma.StringNullableFilter<"QuestionType"> | string | null
  isActive?: Prisma.BoolFilter<"QuestionType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"QuestionType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionType"> | Date | string
}

export type QuestionTypeCreateWithoutChapterInput = {
  id?: string
  name: string
  displayName: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subject: Prisma.AcademicSubjectCreateNestedOneWithoutQuestionTypesInput
}

export type QuestionTypeUncheckedCreateWithoutChapterInput = {
  id?: string
  name: string
  displayName: string
  subjectId: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionTypeCreateOrConnectWithoutChapterInput = {
  where: Prisma.QuestionTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionTypeCreateWithoutChapterInput, Prisma.QuestionTypeUncheckedCreateWithoutChapterInput>
}

export type QuestionTypeCreateManyChapterInputEnvelope = {
  data: Prisma.QuestionTypeCreateManyChapterInput | Prisma.QuestionTypeCreateManyChapterInput[]
  skipDuplicates?: boolean
}

export type QuestionTypeUpsertWithWhereUniqueWithoutChapterInput = {
  where: Prisma.QuestionTypeWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionTypeUpdateWithoutChapterInput, Prisma.QuestionTypeUncheckedUpdateWithoutChapterInput>
  create: Prisma.XOR<Prisma.QuestionTypeCreateWithoutChapterInput, Prisma.QuestionTypeUncheckedCreateWithoutChapterInput>
}

export type QuestionTypeUpdateWithWhereUniqueWithoutChapterInput = {
  where: Prisma.QuestionTypeWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionTypeUpdateWithoutChapterInput, Prisma.QuestionTypeUncheckedUpdateWithoutChapterInput>
}

export type QuestionTypeUpdateManyWithWhereWithoutChapterInput = {
  where: Prisma.QuestionTypeScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionTypeUpdateManyMutationInput, Prisma.QuestionTypeUncheckedUpdateManyWithoutChapterInput>
}

export type QuestionTypeCreateManySubjectInput = {
  id?: string
  name: string
  displayName: string
  chapterId?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionTypeUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapter?: Prisma.AcademicChapterUpdateOneWithoutQuestionTypesNestedInput
}

export type QuestionTypeUncheckedUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionTypeUncheckedUpdateManyWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionTypeCreateManyChapterInput = {
  id?: string
  name: string
  displayName: string
  subjectId: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionTypeUpdateWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject?: Prisma.AcademicSubjectUpdateOneRequiredWithoutQuestionTypesNestedInput
}

export type QuestionTypeUncheckedUpdateWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionTypeUncheckedUpdateManyWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type QuestionTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  subjectId?: boolean
  chapterId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.QuestionType$chapterArgs<ExtArgs>
}, ExtArgs["result"]["questionType"]>

export type QuestionTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  subjectId?: boolean
  chapterId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.QuestionType$chapterArgs<ExtArgs>
}, ExtArgs["result"]["questionType"]>

export type QuestionTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  subjectId?: boolean
  chapterId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.QuestionType$chapterArgs<ExtArgs>
}, ExtArgs["result"]["questionType"]>

export type QuestionTypeSelectScalar = {
  id?: boolean
  name?: boolean
  displayName?: boolean
  subjectId?: boolean
  chapterId?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type QuestionTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "displayName" | "subjectId" | "chapterId" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["questionType"]>
export type QuestionTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.QuestionType$chapterArgs<ExtArgs>
}
export type QuestionTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.QuestionType$chapterArgs<ExtArgs>
}
export type QuestionTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.AcademicSubjectDefaultArgs<ExtArgs>
  chapter?: boolean | Prisma.QuestionType$chapterArgs<ExtArgs>
}

export type $QuestionTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuestionType"
  objects: {
    subject: Prisma.$AcademicSubjectPayload<ExtArgs>
    chapter: Prisma.$AcademicChapterPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    displayName: string
    subjectId: string
    chapterId: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["questionType"]>
  composites: {}
}

export type QuestionTypeGetPayload<S extends boolean | null | undefined | QuestionTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload, S>

export type QuestionTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuestionTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuestionTypeCountAggregateInputType | true
  }

export interface QuestionTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuestionType'], meta: { name: 'QuestionType' } }
  /**
   * Find zero or one QuestionType that matches the filter.
   * @param {QuestionTypeFindUniqueArgs} args - Arguments to find a QuestionType
   * @example
   * // Get one QuestionType
   * const questionType = await prisma.questionType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuestionTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, QuestionTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuestionType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuestionTypeFindUniqueOrThrowArgs} args - Arguments to find a QuestionType
   * @example
   * // Get one QuestionType
   * const questionType = await prisma.questionType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuestionTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuestionTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionTypeFindFirstArgs} args - Arguments to find a QuestionType
   * @example
   * // Get one QuestionType
   * const questionType = await prisma.questionType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuestionTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, QuestionTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionTypeFindFirstOrThrowArgs} args - Arguments to find a QuestionType
   * @example
   * // Get one QuestionType
   * const questionType = await prisma.questionType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuestionTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuestionTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuestionTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuestionTypes
   * const questionTypes = await prisma.questionType.findMany()
   * 
   * // Get first 10 QuestionTypes
   * const questionTypes = await prisma.questionType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const questionTypeWithIdOnly = await prisma.questionType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuestionTypeFindManyArgs>(args?: Prisma.SelectSubset<T, QuestionTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuestionType.
   * @param {QuestionTypeCreateArgs} args - Arguments to create a QuestionType.
   * @example
   * // Create one QuestionType
   * const QuestionType = await prisma.questionType.create({
   *   data: {
   *     // ... data to create a QuestionType
   *   }
   * })
   * 
   */
  create<T extends QuestionTypeCreateArgs>(args: Prisma.SelectSubset<T, QuestionTypeCreateArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuestionTypes.
   * @param {QuestionTypeCreateManyArgs} args - Arguments to create many QuestionTypes.
   * @example
   * // Create many QuestionTypes
   * const questionType = await prisma.questionType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuestionTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, QuestionTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuestionTypes and returns the data saved in the database.
   * @param {QuestionTypeCreateManyAndReturnArgs} args - Arguments to create many QuestionTypes.
   * @example
   * // Create many QuestionTypes
   * const questionType = await prisma.questionType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuestionTypes and only return the `id`
   * const questionTypeWithIdOnly = await prisma.questionType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuestionTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuestionTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuestionType.
   * @param {QuestionTypeDeleteArgs} args - Arguments to delete one QuestionType.
   * @example
   * // Delete one QuestionType
   * const QuestionType = await prisma.questionType.delete({
   *   where: {
   *     // ... filter to delete one QuestionType
   *   }
   * })
   * 
   */
  delete<T extends QuestionTypeDeleteArgs>(args: Prisma.SelectSubset<T, QuestionTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuestionType.
   * @param {QuestionTypeUpdateArgs} args - Arguments to update one QuestionType.
   * @example
   * // Update one QuestionType
   * const questionType = await prisma.questionType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuestionTypeUpdateArgs>(args: Prisma.SelectSubset<T, QuestionTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuestionTypes.
   * @param {QuestionTypeDeleteManyArgs} args - Arguments to filter QuestionTypes to delete.
   * @example
   * // Delete a few QuestionTypes
   * const { count } = await prisma.questionType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuestionTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuestionTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuestionTypes
   * const questionType = await prisma.questionType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuestionTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, QuestionTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionTypes and returns the data updated in the database.
   * @param {QuestionTypeUpdateManyAndReturnArgs} args - Arguments to update many QuestionTypes.
   * @example
   * // Update many QuestionTypes
   * const questionType = await prisma.questionType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuestionTypes and only return the `id`
   * const questionTypeWithIdOnly = await prisma.questionType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuestionTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuestionTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuestionType.
   * @param {QuestionTypeUpsertArgs} args - Arguments to update or create a QuestionType.
   * @example
   * // Update or create a QuestionType
   * const questionType = await prisma.questionType.upsert({
   *   create: {
   *     // ... data to create a QuestionType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuestionType we want to update
   *   }
   * })
   */
  upsert<T extends QuestionTypeUpsertArgs>(args: Prisma.SelectSubset<T, QuestionTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__QuestionTypeClient<runtime.Types.Result.GetResult<Prisma.$QuestionTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuestionTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionTypeCountArgs} args - Arguments to filter QuestionTypes to count.
   * @example
   * // Count the number of QuestionTypes
   * const count = await prisma.questionType.count({
   *   where: {
   *     // ... the filter for the QuestionTypes we want to count
   *   }
   * })
  **/
  count<T extends QuestionTypeCountArgs>(
    args?: Prisma.Subset<T, QuestionTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuestionTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuestionType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuestionTypeAggregateArgs>(args: Prisma.Subset<T, QuestionTypeAggregateArgs>): Prisma.PrismaPromise<GetQuestionTypeAggregateType<T>>

  /**
   * Group by QuestionType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuestionTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuestionTypeGroupByArgs['orderBy'] }
      : { orderBy?: QuestionTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuestionTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuestionTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuestionType model
 */
readonly fields: QuestionTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuestionType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuestionTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subject<T extends Prisma.AcademicSubjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicSubjectDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicSubjectClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chapter<T extends Prisma.QuestionType$chapterArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionType$chapterArgs<ExtArgs>>): Prisma.Prisma__AcademicChapterClient<runtime.Types.Result.GetResult<Prisma.$AcademicChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuestionType model
 */
export interface QuestionTypeFieldRefs {
  readonly id: Prisma.FieldRef<"QuestionType", 'String'>
  readonly name: Prisma.FieldRef<"QuestionType", 'String'>
  readonly displayName: Prisma.FieldRef<"QuestionType", 'String'>
  readonly subjectId: Prisma.FieldRef<"QuestionType", 'String'>
  readonly chapterId: Prisma.FieldRef<"QuestionType", 'String'>
  readonly isActive: Prisma.FieldRef<"QuestionType", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"QuestionType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"QuestionType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuestionType findUnique
 */
export type QuestionTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * Filter, which QuestionType to fetch.
   */
  where: Prisma.QuestionTypeWhereUniqueInput
}

/**
 * QuestionType findUniqueOrThrow
 */
export type QuestionTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * Filter, which QuestionType to fetch.
   */
  where: Prisma.QuestionTypeWhereUniqueInput
}

/**
 * QuestionType findFirst
 */
export type QuestionTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * Filter, which QuestionType to fetch.
   */
  where?: Prisma.QuestionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionTypes to fetch.
   */
  orderBy?: Prisma.QuestionTypeOrderByWithRelationInput | Prisma.QuestionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionTypes.
   */
  cursor?: Prisma.QuestionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionTypes.
   */
  distinct?: Prisma.QuestionTypeScalarFieldEnum | Prisma.QuestionTypeScalarFieldEnum[]
}

/**
 * QuestionType findFirstOrThrow
 */
export type QuestionTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * Filter, which QuestionType to fetch.
   */
  where?: Prisma.QuestionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionTypes to fetch.
   */
  orderBy?: Prisma.QuestionTypeOrderByWithRelationInput | Prisma.QuestionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionTypes.
   */
  cursor?: Prisma.QuestionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionTypes.
   */
  distinct?: Prisma.QuestionTypeScalarFieldEnum | Prisma.QuestionTypeScalarFieldEnum[]
}

/**
 * QuestionType findMany
 */
export type QuestionTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * Filter, which QuestionTypes to fetch.
   */
  where?: Prisma.QuestionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionTypes to fetch.
   */
  orderBy?: Prisma.QuestionTypeOrderByWithRelationInput | Prisma.QuestionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuestionTypes.
   */
  cursor?: Prisma.QuestionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionTypes.
   */
  skip?: number
  distinct?: Prisma.QuestionTypeScalarFieldEnum | Prisma.QuestionTypeScalarFieldEnum[]
}

/**
 * QuestionType create
 */
export type QuestionTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a QuestionType.
   */
  data: Prisma.XOR<Prisma.QuestionTypeCreateInput, Prisma.QuestionTypeUncheckedCreateInput>
}

/**
 * QuestionType createMany
 */
export type QuestionTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuestionTypes.
   */
  data: Prisma.QuestionTypeCreateManyInput | Prisma.QuestionTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuestionType createManyAndReturn
 */
export type QuestionTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * The data used to create many QuestionTypes.
   */
  data: Prisma.QuestionTypeCreateManyInput | Prisma.QuestionTypeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionType update
 */
export type QuestionTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a QuestionType.
   */
  data: Prisma.XOR<Prisma.QuestionTypeUpdateInput, Prisma.QuestionTypeUncheckedUpdateInput>
  /**
   * Choose, which QuestionType to update.
   */
  where: Prisma.QuestionTypeWhereUniqueInput
}

/**
 * QuestionType updateMany
 */
export type QuestionTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuestionTypes.
   */
  data: Prisma.XOR<Prisma.QuestionTypeUpdateManyMutationInput, Prisma.QuestionTypeUncheckedUpdateManyInput>
  /**
   * Filter which QuestionTypes to update
   */
  where?: Prisma.QuestionTypeWhereInput
  /**
   * Limit how many QuestionTypes to update.
   */
  limit?: number
}

/**
 * QuestionType updateManyAndReturn
 */
export type QuestionTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * The data used to update QuestionTypes.
   */
  data: Prisma.XOR<Prisma.QuestionTypeUpdateManyMutationInput, Prisma.QuestionTypeUncheckedUpdateManyInput>
  /**
   * Filter which QuestionTypes to update
   */
  where?: Prisma.QuestionTypeWhereInput
  /**
   * Limit how many QuestionTypes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionType upsert
 */
export type QuestionTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the QuestionType to update in case it exists.
   */
  where: Prisma.QuestionTypeWhereUniqueInput
  /**
   * In case the QuestionType found by the `where` argument doesn't exist, create a new QuestionType with this data.
   */
  create: Prisma.XOR<Prisma.QuestionTypeCreateInput, Prisma.QuestionTypeUncheckedCreateInput>
  /**
   * In case the QuestionType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuestionTypeUpdateInput, Prisma.QuestionTypeUncheckedUpdateInput>
}

/**
 * QuestionType delete
 */
export type QuestionTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
  /**
   * Filter which QuestionType to delete.
   */
  where: Prisma.QuestionTypeWhereUniqueInput
}

/**
 * QuestionType deleteMany
 */
export type QuestionTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionTypes to delete
   */
  where?: Prisma.QuestionTypeWhereInput
  /**
   * Limit how many QuestionTypes to delete.
   */
  limit?: number
}

/**
 * QuestionType.chapter
 */
export type QuestionType$chapterArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicChapter
   */
  select?: Prisma.AcademicChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicChapter
   */
  omit?: Prisma.AcademicChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicChapterInclude<ExtArgs> | null
  where?: Prisma.AcademicChapterWhereInput
}

/**
 * QuestionType without action
 */
export type QuestionTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionType
   */
  select?: Prisma.QuestionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionType
   */
  omit?: Prisma.QuestionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionTypeInclude<ExtArgs> | null
}
